window.nomesHomens = [
  "Lucas Moreira", "Rafael Lima", "João Victor Souza", "Marcos Henrique", "Bruno Ferreira",
  "Felipe Duarte", "Gustavo Alves", "Leandro Martins", "Daniel Cardoso", "Caio Mendes",
  "Rodrigo Nogueira", "Thiago Costa", "Matheus Silveira", "Alexandre Rocha", "Diego Ramos",
  "Vinícius Andrade", "Eduardo Pinto", "Pedro Augusto", "Gabriel Oliveira", "André Faria",
  "Jorge Luiz", "Robson Batista", "Carlos Eduardo", "Wellington Araújo", "Renato Cunha",
  "Wallace Moraes", "Igor Santana", "Fábio Barreto", "Jefferson Dias", "Samuel Ribeiro",
  "Douglas Freitas", "Marcelo Araújo", "Bruno Batista", "Maurício Tavares", "Alexandre Almeida",
  "Sérgio Machado", "Fernando Reis", "Ricardo Lopes", "Cláudio Pires", "Renan Soares",
  "Anderson Borges", "Juliano Peixoto", "Sandro Mattos", "William Silva", "Roberto Moura",
  "Leonardo Monteiro", "César Barros", "André Luiz", "Renato Silva", "Cristiano Castro",
  "Guilherme Teixeira", "Henrique Carvalho", "Evandro Mendes", "Danilo Ferreira", "Luciano Barroso",
  "Gilberto Faria", "Paulo Sérgio", "Everton Assis", "Alex Sandro", "Rogério Nascimento",
  "Raphael Carvalho", "Marcelo Lopes", "Robson Oliveira", "Felipe Mattos", "Anderson Martins",
  "Fernando Cardoso", "Bruno Ribeiro", "Luciano Souza", "Leandro Correia", "Eduardo Bastos",
  "Edson Miranda", "Marcelo Brito", "Júlio César", "André Castro", "Douglas Henrique",
  "Fernando Augusto", "Alexandre Mendes", "Rafael Rocha", "Rodrigo Castro", "Márcio Garcia",
  "Patrick Siqueira", "Leonardo Pinheiro", "Sandro Pereira", "Diego Machado", "Wesley Couto",
  "Edgar Oliveira", "Antônio Figueiredo", "Cássio Moraes", "André Santos", "Hugo Vasconcelos",
  "Ricardo Pereira", "Roberto Teixeira", "Bruno Monteiro", "Alex Silva", "Fábio Ramos",
  "José Ricardo", "Carlos Henrique", "Gilmar Souza", "Fabiano Alves", "Otávio Duarte",
  "Ailton Soares", "Washington Torres", "Rafael Bastos", "Marcos Vinícius", "Davi Mattos",
  "Augusto Nunes", "Danilo Rocha", "Marcio Pinheiro", "Cristiano Lopes", "Vitor Andrade",
  "Paulo César", "Sandro Nascimento", "João Paulo", "Érico Almeida", "Lucas Barbosa"
];
