  const programmedMessages = [   
{ time: "00:00:14", name: "Iara", text: "Boa noite, como vai?" },
{ time: "00:00:30", name: "Juliana", text: "Oba, começou.. esperei a semana toda" },
{ time: "00:01:00", name: "Mercia", text: "Pode chamar quem não está no grupo?" },
{ time: "00:01:01", name: "Luciana", text: "Boa noite" },
{ time: "00:01:10", name: "Fabia", text: "boa noite🙌" },
{ time: "00:01:20", name: "Iracelma", text: "boa noiteee!" },
{ time: "00:01:27", name: "Mercia", text: "Ta bom, pode deixar, vou avisar" },
{ time: "00:01:29", name: "Renira", text: "Boa noite! Como vai?" },
{ time: "00:01:33", name: "Priscila", text: "Boa noite, kkkk" },
{ time: "00:01:35", name: "Meire", text: "Noitee, vai ficar gravada?" },
{ time: "00:01:40", name: "Marcia", text: "Esperei a semana toda" },
{ time: "00:01:45", name: "Fatima", text: "Espero que você possa me ajudar, eu preciso emagrecer." },
{ time: "00:02:00", name: "Silva", text: "Vai começar!!!" },
{ time: "00:02:01", name: "Ana", text: "Vamos juntos" },
{ time: "00:02:14", name: "Lays", text: "Domingo abençoado para nós 🙌" },
{ time: "00:02:24", name: "Zenilda", text: "Douglas eu me comprometo" },
{ time: "00:02:26", name: "Flaviane", text: "Eu estou contigo" },
{ time: "00:02:30", name: "Caleane", text: "kkkkk tmj" },
{ time: "00:02:31", name: "Iara", text: "Eu me comprometo" },
{ time: "00:02:32", name: "Mercia", text: "Começou agora?" },
{ time: "00:02:33", name: "Ana", text: "Eu estou fazendo dieta com uma que o nutri, mas não to vendo efeito...😔😔😔" },
{ time: "00:02:39", name: "Zilda", text: "Eu também estou perdida" },
{ time: "00:02:43", name: "Iara", text: "já chamei, vou chamar mais gente então" },
{ time: "00:02:44", name: "Nubia", text: "Posso enviar o link que está no grupo então!" },
{ time: "00:02:50", name: "Kesia", text: "Eu já não acredito em mais nada" },
{ time: "00:02:50", name: "Pri", text: "Meu metabolismo é lento acho que é minha tireóide" },
{ time: "00:03:10", name: "Jucelia", text: "Eu já fiz muita dieta" },
{ time: "00:03:20", name: "Angela", text: "Eu vi o comentário dela" },
{ time: "00:04:00", name: "Zenilda", text: "Eu vi isso" },
{ time: "00:04:01", name: "Flaviane", text: "Vamos que vamos!!!😃😃😃" },
{ time: "00:04:01", name: "Nubia", text: "Eu estou confiante" },
{ time: "00:04:03", name: "Debora", text: "Tamo junto" },
{ time: "00:04:07", name: "Julia", text: "Vai ficar gravada???" },
{ time: "00:04:20", name: "Katiane", text: "Já cai em mentira mais!" },
{ time: "00:04:10", name: "Iara", text: "Já fiz dieta do ovo" },
{ time: "00:05:06", name: "Sara", text: "Realmente eu já não sei mais o que funciona..." },
{ time: "00:05:07", name: "Isa", text: "Cada um fala uma coisa" },
{ time: "00:05:16", name: "Rafaela", text: "Eu estou com esperanças" },
{ time: "00:05:17", name: "Dani", text: "verdade... eu vou dar mais essa chance" },
{ time: "00:05:18", name: "Juventite", text: "Eu estou comprometida" },
{ time: "00:07:00", name: "Luciana", text: "Eu estou pra desistir, vamos ver o que você vai mostrar..." },
{ time: "00:07:28", name: "Marcela", text: "Estou tomando mounjaru e só estou passando mal, uma dor terrivel de estomago😓😓" },
{ time: "00:08:10", name: "Juliana", text: "Estou contigo, já desmarquei tudo que tinha hoje pra assistir" },
{ time: "00:08:11", name: "Mercia", text: "Vamos até o fim!!!" },
{ time: "00:08:25", name: "Flaviane", text: "Estou confiante que agora vai....👍👍👍" },
{ time: "00:08:30", name: "Angelina", text: "Tudo certo Douglas, vamos lá!!!!" },
{ time: "00:08:35", name: "Katianne", text: "Quero descobrir hoje aonde estou errando" },
{ time: "00:08:36", name: "Isa", text: "Tudo ok, vou me libertar" },
{ time: "00:09:30", name: "Iracelma", text: "Eu amo arroz e feijão!!!" },
{ time: "00:09:06", name: "Iara", text: "Pão é tudo de bom, com manteiga!!!" },
{ time: "00:09:37", name: "Manu", text: "Já não sei mais o que fazer😔" },
{ time: "00:09:38", name: "Pietra", text: "Já não aguento mais ficar com esse peso!" },
{ time: "00:09:17", name: "Pietra", text: "Chocolaté eu gosto, não do conta de comer pouco" },
{ time: "00:10:26", name: "Isa", text: "Está ao vivo??" },
{ time: "00:10:26", name: "Rafaela", text: "Vai ficar gravada Douglas" },
{ time: "00:09:40", name: "Isa", text: "Eu amo arroz e pãozinho não abro mão" },
{ time: "00:10:30", name: "Iracelma", text: "Estou com esparança, só preciso perder 16kg, será que da?" },
{ time: "00:10:31", name: "Iara", text: "👍👍👍👍 Estou confiante" },
{ time: "00:10:32", name: "Manu", text: "Eu tenho 62 anos, sera que ainda consigo emagrecer?" },
{ time: "00:11:00", name: "Debora", text: "Já fiz dieta da Lua, só passei fome" },
{ time: "00:10:59", name: "Dani", text: "Eu já não acredito mais" },
{ time: "00:11:01", name: "Fabia", text: "Já tentei de tudo" },
{ time: "00:11:43", name: "Isa", text: "Quando eu era mais nova, era mais facil mesmo" },
{ time: "00:11:44", name: "Iracelma", text: "Eu concordo com isso que vc disse!" },
{ time: "00:11:37", name: "Iara", text: "Meu metabolismo é lento,o que fazer" },
{ time: "00:11:45", name: "Manu", text: "Tamo junto, vamos lá" },
{ time: "00:11:50", name: "Pietra", text: "👍👍👍eu perciso perder 12kg" },
{ time: "00:11:52", name: "Isa", text: "Boraaa" },
{ time: "00:11:55", name: "Rafaela", text: "To junto" },
{ time: "00:12:22", name: "Zilda", text: "Quero até ver essa do abacate" },
{ time: "00:12:27", name: "Fabia", text: "Como eu emagreço comendo abacate?" },
{ time: "00:13:18", name: "Meire", text: "Que legal o depoimento dela" },
{ time: "00:13:23", name: "Jucelia", text: "Eu já não como arroz tem tanto tempo, e eu amo arroz😔" },
{ time: "00:13:27", name: "Nubia", text: "Refrigerante também é bom em..." },
{ time: "00:13:30", name: "Regina", text: "O mais difícil é controlar a fome que vem forte" },
{ time: "00:13:52", name: "Odete", text: "Mas açucar não faz mal???" },
{ time: "00:14:00", name: "Laura", text: "Eu tive a infancia assim também!" },
{ time: "00:14:10", name: "Manu", text: "Não acredito que consigo emagrecer comendo bem😔" },
{ time: "00:15:29", name: "Iara", text: "Que triste isso" },
{ time: "00:15:32", name: "Layz", text: "Que mulher ignorante" },
{ time: "00:15:30", name: "Nubia", text: "Isso é verdade" },
{ time: "00:15:34", name: "Carla", text: "Já passei pro isso" },
{ time: "00:15:35", name: "Odete", text: "Eu como só salada e carne" },
{ time: "00:15:40", name: "Maisa", text: "Não é possivel 25kg, quero saber" },
{ time: "00:10:50", name: "Samanta", text: "Vamos juntas, meninas!!!" },
{ time: "00:16:04", name: "Zilda", text: "Ele disse que não vai ficar gravada" },
{ time: "00:16:10", name: "Manu", text: "Porque tem pessoas que conseguem mais facil?" },
{ time: "00:16:12", name: "Angelina", text: "Eu tenho tireóide é possível emagrecer?" },
{ time: "00:16:13", name: "Katianne", text: "Douglas, mesmo eu fazendo dieta não funciona" },
{ time: "00:16:14", name: "Lara", text: "Eu acredito que deve ter algum segredo não é possível" },
{ time: "00:16:14", name: "simone", text: "hahahaha" },
{ time: "00:16:17", name: "Neli", text: "👍" },
{ time: "00:16:19", name: "Flaviane", text: "Alguem de Maceió??" },
{ time: "00:16:22", name: "Pietra", text: "Boa noite, começou agora?" },
{ time: "00:17:09", name: "Kesia", text: "Quero saber do abacate" },
{ time: "00:17:20", name: "Zilda", text: "Interessante quero saber o que você fez" },
{ time: "00:18:15", name: "Meire", text: "Meu metabolismo é super lento" },
{ time: "00:18:48", name: "Dani", text: "Eu passo por todos esses problemas que você disse" },
{ time: "00:18:49", name: "Iara", text: "Já tomei muito remédio e nunca deu certo" },
{ time: "00:19:35", name: "Nubia", text: "Realmente eu vivo isso todos os dias" },
{ time: "00:19:40", name: "Carla", text: "Eu estou choacada com isso" },
{ time: "00:19:46", name: "Odete", text: "comendo só um pouco engorda 3kg" },
{ time: "00:19:57", name: "Meire", text: "Meus parabéns, muito bacana" },
{ time: "00:21:30", name: "Dani", text: "Nossa, eu engordo muito facil" },
{ time: "00:21:31", name: "Ydiara", text: "Caramba ela perdeu tudo isso?" },
{ time: "00:22:35", name: "Ana Clara", text: "É só comer abacate na dieta???" },
{ time: "00:23:00", name: "Iara", text: "Triptofano!!!" },
{ time: "00:23:28", name: "Sara", text: "Eu quero" },
{ time: "00:23:29", name: "Isa", text: "Interessante eu gostei..." },
{ time: "00:23:30", name: "Jucelina", text: "isso vai me deixar sem fome, eu vou comer menos é isso?" },
{ time: "00:23:51", name: "Lara", text: "estou chocara" },
{ time: "00:23:58", name: "Kesia", text: "Que legal, gostei" },
{ time: "00:23:59", name: "Layz", text: "Bloquear a gordura, já vi algo parecido" },
{ time: "00:24:01", name: "Renira", text: "que legal, eu percebo que meu coco fica com gordura no vaso" },
{ time: "00:24:23", name: "Zenia", text: "Você podia ajudar a gente" },
{ time: "00:24:33", name: "Zenia", text: "será que agora eu consigo emagrecer Douglas😭😭" },
{ time: "00:24:47", name: "Katianne", text: "econtr aonde esses produtos???" },
{ time: "00:24:58", name: "Iara", text: "Nunca ouv falar, onde compra" },
{ time: "00:25:24", name: "Mercia", text: "mounjaro é muito caro" },
{ time: "00:25:42", name: "Ana", text: "é ótimo esses eu já tomei" },
{ time: "00:26:18", name: "Marcia", text: "Eu tenho dificudlade de emagrecer " },
{ time: "00:26:30", name: "Lucia", text: "Não consigo perder nenhuma grama" },
{ time: "00:26:44", name: "Josy", text: "É até dificil de acreditar que faz tudo isso 20Kg é interessante" },
{ time: "00:26:57", name: "Fabia", text: "é maravilhoso isso em" },
{ time: "00:27:10", name: "Layz", text: "Eu queria um produto assim" },
{ time: "00:27:26", name: "Iara", text: "Que legal essas substâncias, onde compra?" },
{ time: "00:27:32", name: "Mercia", text: "que legal" },
{ time: "00:27:51", name: "Flores", text: "Será que ele vai passar pra gente" },
{ time: "00:27:55", name: "Meire", text: "E quero fazer o acopanhamento com você!!!" },
{ time: "00:28:20", name: "Meire", text: "Essa é a fórmula do abacate então" },
{ time: "00:28:53", name: "Layane", text: "Que maravilhoso, já quero" },
{ time: "00:28:56", name: "Jucelia", text: "Quero perder muito peso..." },
{ time: "00:28:59", name: "Luciana", text: "O que são macros?" },
{ time: "00:29:00", name: "Zenilda", text: "essas mulheres estão magras ainda depois de tomar?" },
{ time: "00:29:01", name: "flaviane", text: "Conheço seu trabalho, eu confio" },
{ time: "00:29:05", name: "Debora", text: "Eu vou começar, como faz?" },
{ time: "00:29:18", name: "Fabia", text: "Gostei, tem como contratar???" },
{ time: "00:29:20", name: "Meire", text: "Fabia, vamos fazer amiga!" },
{ time: "00:30:35", name: "Iracelma", text: "Eu gostei" },
{ time: "00:30:38", name: "Margareth", text: "Estou aqui..." },
{ time: "00:30:39", name: "Isa", text: "para mim faz sentido agora" },
{ time: "00:30:40", name: "simone", text: "Legal, não sabia diso" },
{ time: "00:30:25", name: "Kesia", text: "Muito legal" },
{ time: "00:31:30", name: "Laura", text: "Parabéns, eu vou começar" },
{ time: "00:31:39", name: "flaviane", text: "Aonde encontra?" },
{ time: "00:31:42", name: "Odete", text: "Que lega, também quero!" },
{ time: "00:31:50", name: "Rafaela", text: "adorei já quero" },
{ time: "00:32:01", name: "Luciana", text: "Meus parabéns" },
{ time: "00:32:05", name: "Angela", text: "Eu também quero" },
{ time: "00:32:10", name: "Rubia", text: "Realmente, faz todo sentido" },
{ time: "00:32:15", name: "Paula", text: "Que legal, parabéns Douglas" },
{ time: "00:32:20", name: "Kesia", text: "Muito legal" },
{ time: "00:32:22", name: "Laura", text: "Parabéns" },
{ time: "00:32:35", name: "Ana Clara", text: "Que top, meus parabéns" },
{ time: "00:32:40", name: "Iracelma", text: "Bora que quero mais, estou adorando..." },
{ time: "00:32:41", name: "Iara", text: "Show, vamos firme" },
{ time: "00:33:01", name: "Manu", text: "Como que chama??" },
{ time: "00:33:02", name: "Luci", text: "Quero começar amanhã" },
{ time: "00:33:20", name: "Iara", text: "Vamos lá!!!!!" },
{ time: "00:33:25", name: "Nubia", text: "Eu quero!" },
{ time: "00:33:29", name: "Manu", text: "Estamos preparadas" },
{ time: "00:33:30", name: "Pri", text: "Eu quero muito, estou precisando pra ontem" },
{ time: "00:33:35", name: "Angelina", text: "Vamos láaa👍👍👍" },
{ time: "00:33:36", name: "Katianne", text: "Eu quero" },
{ time: "00:33:40", name: "Lara", text: "Obaaa chegou!!" },
{ time: "00:33:43", name: "simone", text: "reset" },
{ time: "00:33:44", name: "Neli", text: "reset metabólico 👍👍👍" },
{ time: "00:33:45", name: "Iracelma", text: "vamos começar" },
{ time: "00:33:50", name: "Iara", text: "Conte comigo👍" },
{ time: "00:33:55", name: "Manu", text: "Tamo junto" },
{ time: "00:34:26", name: "Layz", text: "Faz sentido, eu gosto de chocolate" },
{ time: "00:34:30", name: "Iracelma", text: "Eu quero fazer, gosto de tomar um cervejinha." },
{ time: "00:34:31", name: "Iara", text: "como faz?" },
{ time: "00:34:40", name: "Manu", text: "Vai fazer desconto pra gente Douglas??" },
{ time: "00:35:08", name: "Layz", text: "Eu quero esse suplemento como faço??" },
{ time: "00:35:10", name: "Mercia", text: "compreendi" },
{ time: "00:35:15", name: "Marcia", text: "Só tem guerreira aqui hoje! Vamos lá meninas..." },
{ time: "00:35:52", name: "Ana", text: "já quero, gosto de produto natural" },
{ time: "00:36:00", name: "Lays", text: "Eu prefiro fazer contigo, como faz?" },
{ time: "00:36:01", name: "Zenilda", text: "todas suas pacientes usam então...eu vou ser a próxima" },
{ time: "00:36:05", name: "Flaviane", text: "👍👍 eu quero seu acompanhamento" },
{ time: "00:36:21", name: "Odete", text: "Você vai acompanhar a gente?!" },
{ time: "00:36:26", name: "Rafaela", text: "adorei já quero" },
{ time: "00:36:37", name: "Renira", text: "É otimo, deve ser maravilhoso esse suplemento" },
{ time: "00:36:40", name: "Zenia", text: "é individual eu gostei por issso!" },
{ time: "00:36:41", name: "Fatima", text: "Você vai passar o que precisa fazer??" },
{ time: "00:36:46", name: "Lucia", text: "Adorei a combinação, parabéns Douglas" },
{ time: "00:36:50", name: "Josy", text: "Parabéns pelo programa, muito legal, como faz para começar?" },
{ time: "00:36:59", name: "Fabia", text: "Adorei, gostei demais." },
{ time: "00:37:29", name: "Lara", text: "Eu quero!!" },
{ time: "00:37:30", name: "simone", text: "eu" },
{ time: "00:37:31", name: "Neli", text: "eu claro👍" },
{ time: "00:37:32", name: "Iracelma", text: "vamos começar" },
{ time: "00:37:33", name: "Iara", text: "Conte comigo👍" },
{ time: "00:37:34", name: "Manu", text: "Tamo junto" },
{ time: "00:37:40", name: "Iara", text: "Aonde compra??" },
{ time: "00:38:34", name: "Zenilda", text: "Eu vou entrar!" },
{ time: "00:38:35", name: "Katiane", text: "Perfeito!!!" },
{ time: "00:38:39", name: "Meire", text: "Eu quero vou comprar agora!!" },
{ time: "00:39:20", name: "Caleane", text: "16kg é um sonho" },
{ time: "00:39:30", name: "Maiza", text: "Perfeito, só do intestino funcionar eu acho ótimo" },
{ time: "00:39:40", name: "Debora", text: "Eu creio, parabéns Douglas" },
{ time: "00:40:11", name: "Renira", text: "Meus parabéns, incrível, estou dentro" },
{ time: "00:41:15", name: "Pricila", text: "ahhhh... eu quero esse acompanhamento" },
{ time: "00:41:20", name: "Meire", text: "Sim, concordo, vou entrar" },
{ time: "00:41:57", name: "Lud", text: "Que linda, eu quero um corpo igual o dela" },
{ time: "00:42:15", name: "Cassia", text: "Ela pace ter ter uns 30 e poucos!!!!!" },
{ time: "00:42:54", name: "Iara", text: "com sua ajuda eu vou fazer com certeza..." },
{ time: "00:42:55", name: "Nubia", text: "Achei legal, me senti confiante" },
{ time: "00:42:59", name: "Manu", text: "Eu vou entrar depois dessa!" },
{ time: "00:43:40", name: "Pri", text: "Eu quero muito, estou precisando pra ontem" },
{ time: "00:43:45", name: "Angelina", text: "Vamos láaa, também quero👍👍👍" },
{ time: "00:43:46", name: "Katianne", text: "Eu quero" },
{ time: "00:43:47", name: "Lara", text: "Incrível esses resultados!!" },
{ time: "00:43:48", name: "simone", text: "eu entre" },
{ time: "00:43:50", name: "Neli", text: "euu 👍👍👍" },
{ time: "00:44:15", name: "Iracelma", text: "vamos começar" },
{ time: "00:44:20", name: "Iara", text: "Bora começar👍" },
{ time: "00:44:21", name: "Manu", text: "Tamo junto" },
{ time: "00:44:07", name: "🤖SUPORTE", text: "7 JÁ ENTRARAM DOUGLAS. RESTAM POUCOAS VAGAS!!!" },
{ time: "00:45:05", name: "Thais", text: "Eu já entrei" },
{ time: "00:45:10", name: "Maria Inês", text: "Comprei e agora?" },
{ time: "00:45:11", name: "Fernanda", text: "tô dentro" },
{ time: "00:45:39", name: "Layz", text: "Eu quero, só clicar no botão??" },
{ time: "00:45:50", name: "Renira", text: "que legal, eu quero" },
{ time: "00:45:55", name: "Zenia", text: "aceita cartão???" },
{ time: "00:46:13", name: "Isa", text: "Eu quero o Triptoplus" },
{ time: "00:46:35", name: "Rafaela", text: "adorei já quero" },
{ time: "00:46:59", name: "Isa", text: "Eu quero" },
{ time: "00:47:01", name: "Iara", text: "Quero começar hoje" },
{ time: "00:47:13", name: "Manu", text: "eu preciso perder 25kg, vou comprar" },
{ time: "00:47:25", name: "Layz", text: "12 meses eu consigo ficar do jeito que eu quero, com sua ajuda" },
{ time: "00:47:37", name: "Mercia", text: "compreendi" },
{ time: "00:48:18", name: "Flores", text: "Vamos lá!" },
{ time: "00:48:28", name: "Luciana", text: "Eu quero fazer o RESET" },
{ time: "00:48:38", name: "simone", text: "Já quero Douglas" },
{ time: "00:48:40", name: "Iracelma", text: "vamos começar" },
{ time: "00:49:02", name: "Katianne", text: "Olha... já tentei tanto, agora não é possível😔😔" },
{ time: "00:49:05", name: "Lara", text: "Ai que sonho" },
{ time: "00:49:34", name: "Raquel", text: "Após o pagamento o que devo fazer?" },
{ time: "00:49:39", name: "🤖SUPORTE", text: "RESTAM POUCAS VAGAS: http://dougleao.com.br/webnar-plano12" },
{ time: "00:49:50", name: "Juliana", text: "Como é a forma de pagamento?" },
{ time: "00:50:10", name: "Marcia S.", text: "Consegue segurar até amanhã?" },
{ time: "00:50:15", name: "Jucelina", text: "Vai até que dia mesmo?" },
{ time: "00:50:20", name: "Carla", text: "Meu marido pode tomar também?" },
{ time: "00:50:35", name: "Jane", text: "Em quanto tempo eu vou receber o suplemento?" },
{ time: "00:50:48", name: "Meire", text: "VIXXXXX😔" },
{ time: "00:50:50", name: "Meire", text: "Posso dar para meu marido?" },
{ time: "00:50:55", name: "Lay", text: "É verdade" },
{ time: "00:50:59", name: "Rosa", text: "Moro no interior, como eu faço?" },
{ time: "00:51:20", name: "Natalia", text: "Aceita pagamento via boleto?" },
{ time: "00:51:36", name: "Marcia", text: "Tem alguma contraindicação???" },
{ time: "00:51:42", name: "🤖SUPORTE", text: "GARANTA SUA VAGA: http://dougleao.com.br/webnar-plano12" },
{ time: "00:51:50", name: "Rosana", text: "Tomo remédio para pressão, posso tomar o Triptoplus?" },
{ time: "00:52:00", name: "Silvia Carlos", text: "Você falou que eu ia perder 12kg e eu já perdi 16, o que eu faço agora?" },
{ time: "00:52:05", name: "Maisa", text: "Posso comprar para minha amiga também?" },
{ time: "00:52:15", name: "Iracelma", text: "O melhor plano é o que eu consigo seguir!!!" },
{ time: "00:52:20", name: "Rosana", text: "Eu tomo remédio para pressão, eu posso tomar?" },
{ time: "00:52:40", name: "Daiane", text: "Você é médico?" },
{ time: "00:52:41", name: "🤖SUPORTE", text: "VAGAS ESGOTANDO!!!" },
{ time: "00:52:59", name: "Samanta", text: "E se eu não conseguir seguir?" },
{ time: "00:53:00", name: "Simone", text: "Adorei demais!!!" },
{ time: "00:53:00", name: "🤖SUPORTE", text: "Instagram:  DOUG.LEAO" },
{ time: "00:53:25", name: "Luciana", text: "A garantia é real mesmo?! Já entrei" },
{ time: "00:53:36", name: "Angelica", text: "Sim, faz sentido" },
{ time: "00:53:50", name: "Jurema", text: "Realmente, não tenho mais tempo para ficar perdendo..." },
{ time: "00:54:04", name: "🤖SUPORTE", text: "CORRE MENINAS!!!" },
{ time: "00:54:45", name: "Zenilda", text: "Realmente eu faço isso😔😔" },
{ time: "00:54:38", name: "Simone", text: "eu perciso de ajuda, vou entrar!!!" },
{ time: "00:53:42", name: "Mariana", text: "Como eu vou receber os acessos?" },
{ time: "00:54:00", name: "Kesia", text: "Acabei de adquirir, obrigada Douglas e a equipe já recebi mensagem" },
{ time: "00:54:30", name: "Laura", text: "Alguém aqui conseguiu o desconto de 100?" },
{ time: "00:54:36", name: "Iara", text: "Alguem aqui comprou?? A página não esta abrindo mais..." },
{ time: "00:54:56", name: "🤖SUPORTE", text: "12 MESES: http://dougleao.com.br/webnar-plano12" },
{ time: "00:55:56", name: "Simone", text: "Parabéns!!!" },
{ time: "00:55:57", name: "🤖SUPORTE", text: "12 VAGAS" },
{ time: "0:56:40", name: "Mercia", text: "Tá vou te chamar no privado para tirar algumas dúvidas..." },
{ time: "0:56:50", name: "Manu", text: "Muito obrigada, foi sensacional" },
{ time: "00:56:00", name: "Layz", text: "Gostei muito, adorei" },
{ time: "00:56:32", name: "Dani", text: "Parabéns Douglas, belíssimo trabalho" },
{ time: "00:57:10", name: "🤖SUPORTE", text: "RESET Metabólico: 12 MESES: http://dougleao.com.br/webnar-plano12" },
{ time: "00:57:15", name: "Fabia", text: "Que linda!!" },
{ time: "00:57:40", name: "Neli", text: "Já entrei, vou começar amanhã" },
{ time: "00:57:44", name: "Debora", text: "Boa meninas!!" },
{ time: "00:58:49", name: "Ana Paula", text: "Ainda tem o deconto??" },
{ time: "00:58:59", name: "Maria Clara", text: "Será que a equipe vai enviar novamente o link ou esgotou?" },
{ time: "00:59:00", name: "Layz", text: "Ja tomei ozempic" },
{ time: "00:59:05", name: "Renira", text: "Já tomei tanta coisa, essa é a última que vou tentar.🙏🙏" },
{ time: "00:59:30", name: "Zenia", text: "Ozempic" },
{ time: "00:59:31", name: "Zenia", text: "Detox, e nunca tive resultado" },
{ time: "00:59:40", name: "🤖SUPORTE", text: "Ainda restam algunas vagas meninas, corre que da tempo!!" },
{ time: "00:59:05", name: "Katianne", text: "Olha... ninguem nunca me ensino isso😔😔" },
{ time: "00:59:15", name: "🤖SUPORTE", text: "ÚLTIMAS VAGAS" },
{ time: "00:59:16", name: "🤖SUPORTE", text: "corre: http://dougleao.com.br/webnar-plano12" },
{ time: "00:59:20", name: "Katia", text: "Parabéns Douglas, por entregar tanto...." },
{ time: "00:59:30", name: "Angelina", text: "Eu só conhecia as dietas kkkk mas não sabia porque dava errado" },
{ time: "00:59:34", name: "Lara", text: "Ai que sonho" },
{ time: "01:00:40", name: "Nubia", text: "Eu quero um resultado deste!!" },
{ time: "01:00:50", name: "Kesia", text: "Que linda" },
{ time: "01:01:00", name: "Zilda", text: "Adorei, quero começar também" },
{ time: "01:01:14", name: "🤖SUPORTE", text: "ENCERRANDO EM BREVE...🏃" },
{ time: "01:01:20", name: "Pri", text: "Parabéns para vocês que conseguiram, ficaram muito bonitas" },
{ time: "01:01:22", name: "🤖SUPORTE", text: "ÚLTIMA VAGA: http://dougleao.com.br/webnar-plano12" },
{ time: "01:01:42", name: "Jucelia", text: "A próxima será eu!!!😃😃" },
{ time: "01:01:49", name: "Zenilda", text: "Realmente não tem como ter desculpa" },
{ time: "01:01:50", name: "Zilda", text: "Quem ai conseguiu comprar? Não esta abrindo aqui pra mim" },
{ time: "01:02:00", name: "Pri", text: "Parabéns para vocês, lindas" },
{ time: "01:02:10", name: "Jucelia", text: "Boa noite, obrigado meninas" },
{ time: "01:02:15", name: "🤖SUPORTE", text: "Encerrando transmissão em 15 segundos!" }

		
    ];
