  const programmedMessages = [   
{ time: "00:00:30", name: "Juliana", text: "Oba, começou.. esperei a semana toda" },
{ time: "00:01:00", name: "Mercia", text: "Pode chamar quem não está no grupo?" },
{ time: "00:01:01", name: "Luciana", text: "Boa noite" },
{ time: "00:01:10", name: "Fabia", text: "boa noite🙌" },
{ time: "00:01:20", name: "Iracelma", text: "boa noiteee!" },
{ time: "00:01:27", name: "Mercia", text: "Ta bom, pode deixar, vou avisar" },
{ time: "00:01:29", name: "Renira", text: "Boa noite! Como vai?" },
{ time: "00:01:33", name: "Priscila", text: "Boa noite" },
{ time: "00:01:35", name: "Meire", text: "Noitee, vai ficar gravada?" },
{ time: "00:01:40", name: "Marcia", text: "Esperei a semana toda" },
{ time: "00:01:45", name: "Fatima", text: "Espero que você possa me ajudar, não aguento mais esse peso." },
{ time: "00:02:00", name: "Silva", text: "Vai começar" },
{ time: "00:02:01", name: "Ana", text: "Ta online será?" },
{ time: "00:02:14", name: "Lays", text: "Domingo abençoado para nós 🙌" },
{ time: "00:02:24", name: "Zenilda", text: "Estou fazendo dieta mas parei de emagrecer" },
{ time: "00:02:26", name: "Flaviane", text: "Jejum e low carb já fiz, só passei fome demais" },
{ time: "00:02:30", name: "Caleane", text: "kkkkk Deus me livre de dieta" },
{ time: "00:02:31", name: "Iara", text: "Vai falar do Mounjaro" },
{ time: "00:02:32", name: "Mercia", text: "Começou agora?" },
{ time: "00:02:33", name: "Ana", text: "Eu estou fazendo dieta com uma que o nutri, mas não to vendo efeito...😔😔😔" },
{ time: "00:02:43", name: "Iara", text: "já chamei, vou chamar mais gente então" },
{ time: "00:02:44", name: "Nubia", text: "Posso enviar o link que está no grupo então!" },
{ time: "00:02:50", name: "Kesia", text: "Eu já não acredito em mais nada" },
{ time: "00:02:39", name: "Zilda", text: "Até Ozempic, não funciona será?" },
{ time: "00:02:50", name: "Pri", text: "Meu metabolismo é lento acho que é minha tireóide" },
{ time: "00:03:10", name: "Jucelia", text: "Começou agora????" },
{ time: "00:03:20", name: "Angela", text: "Está ao vivo????" },
{ time: "00:04:00", name: "Zenilda", text: "Eu vi isso" },
{ time: "00:04:01", name: "Flaviane", text: "Vamos que vamos!!!😃😃😃" },
{ time: "00:04:01", name: "Nubia", text: "Aguardei a semana inteira" },
{ time: "00:04:03", name: "Debora", text: "Tamo junto" },
{ time: "00:04:07", name: "Julia", text: "Vai ficar gravada???" },
{ time: "00:04:20", name: "Katiane", text: "Já cai em mentira mais!" },
{ time: "00:04:10", name: "Iara", text: "eu vi esse comentário dela" },
{ time: "00:05:06", name: "Sara", text: "Realmente eu já não sei mais o que funciona..." },
{ time: "00:05:07", name: "Isa", text: "Cada um fala uma coisa" },
{ time: "00:05:46", name: "Rafaela", text: "Eu estou com esperanças" },
{ time: "00:05:50", name: "Dani", text: "verdade... tudo falso, eu vi que nada disso funciona" },
{ time: "00:05:51", name: "Juventite", text: "Eu estou comendo só ovo, funciona?" },
{ time: "00:07:00", name: "Luciana", text: "Eu estou pra desistir, vamos ver o que você vai mostrar..." },
{ time: "00:07:48", name: "Marcela", text: "Estou tomando mounjaru e só estou passando mal, uma dor terrivel de estomago😓😓" },
{ time: "00:08:10", name: "Juliana", text: "Estou contigo, já desmarquei tudo que tinha hoje pra assistir" },
{ time: "00:08:10", name: "Mercia", text: "Vamos até o fim!!!" },
{ time: "00:08:25", name: "Flaviane", text: "Estou confiante que agora vai....👍👍👍" },
{ time: "00:08:30", name: "Angelina", text: "Tudo certo Douglas, vamos lá!!!!" },
{ time: "00:08:35", name: "Katianne", text: "Quero descobrir hoje aonde estou errando" },
{ time: "00:08:36", name: "Isa", text: "Tudo ok, vou me libertar" },
{ time: "00:09:30", name: "Iracelma", text: "Eu amo arroz e feijão!!!" },
{ time: "00:09:36", name: "Iara", text: "Pão é tudo de bom, com manteiga!!!" },
{ time: "00:09:37", name: "Manu", text: "Já não sei mais o que fazer😔" },
{ time: "00:09:38", name: "Pietra", text: "Já não aguento mais ficar com esse peso!" },
{ time: "00:10:25", name: "Pietra", text: "Chocolaté eu gosto, não do conta de comer pouco" },
{ time: "00:10:26", name: "Isa", text: "Está ao vivo??" },
{ time: "00:10:26", name: "Rafaela", text: "Vai ficar gravada Douglas" },
{ time: "00:10:28", name: "Isa", text: "Eu amo arroz e pãozinho não abro mão" },
{ time: "00:10:30", name: "Iracelma", text: "Estou com esparança, só preciso perder 15kg, será que da?" },
{ time: "00:10:31", name: "Iara", text: "👍👍👍👍 Estou confiante" },
{ time: "00:10:32", name: "Manu", text: "Eu tenho 62 anos, sera que ainda consigo emagrecer?" },
{ time: "00:11:00", name: "Debora", text: "Já fiz dieta da Lua, só passei fome" },
{ time: "00:10:59", name: "Dani", text: "Eu já não acredito mais" },
{ time: "00:11:01", name: "Fabia", text: "Já tentei de tudo" },
{ time: "00:11:43", name: "Isa", text: "Antes era mais facil mesmo" },
{ time: "00:11:44", name: "Iracelma", text: "Eu concordo com isso que vc disse!" },
{ time: "00:11:45", name: "Iara", text: "Meu metabolismo é lento,o que fazer" },
{ time: "00:11:45", name: "Manu", text: "Tamo junto, vamos lá" },
{ time: "00:11:50", name: "Pietra", text: "👍👍👍eu perciso perder 12kg" },
{ time: "00:11:52", name: "Isa", text: "Boraaa" },
{ time: "00:11:55", name: "Rafaela", text: "To junto" },
{ time: "00:12:30", name: "Zilda", text: "Quero até ver essa do abacate" },
{ time: "00:12:27", name: "Fabia", text: "Como eu emagreço comendo abacate?" },
{ time: "00:13:18", name: "Meire", text: "Que legal o depoimento dela" },
{ time: "00:13:23", name: "Jucelia", text: "Eu já não como arroz tem tanto tempo, e eu amo arroz😔" },
{ time: "00:13:27", name: "Nubia", text: "Pão também é bom em..." },
{ time: "00:13:30", name: "Regina", text: "O mais difícil é controlar a fome que vem forte" },
{ time: "00:13:52", name: "Odete", text: "Mas açucar não faz mal???" },
{ time: "00:14:00", name: "Laura", text: "Não é possivel, é bom demais pra ser verdade" },
{ time: "00:14:10", name: "Manu", text: "Não acredito que consigo emagrecer comendo tudo isso..." },
{ time: "00:15:29", name: "Iara", text: "Começou... Agora pode contar tudo..." },
{ time: "00:15:32", name: "Layz", text: "Pode contar comigo" },
{ time: "00:15:30", name: "Nubia", text: "Isso é verdade" },
{ time: "00:15:34", name: "Carla", text: "Tamo junto" },
{ time: "00:15:35", name: "Odete", text: "Eu como só salada e carne" },
{ time: "00:15:40", name: "Maisa", text: "Não é possivel, quero saber" },
{ time: "00:10:50", name: "Samanta", text: "Vamos juntas!" },
{ time: "00:16:04", name: "Zilda", text: "Ele disse que não vai ficar gravada" },
{ time: "00:16:10", name: "Manu", text: "Porque tem pessoas que conseguem mais facil?" },
{ time: "00:16:12", name: "Angelina", text: "Eu tenho tireóide é possível emagrecer?" },
{ time: "00:16:13", name: "Katianne", text: "Douglas, mesmo eu fazendo dieta não funciona" },
{ time: "00:16:14", name: "Lara", text: "Eu acredito que deve ter algum segredo não é possível" },
{ time: "00:16:14", name: "simone", text: "hahahaha" },
{ time: "00:16:17", name: "Neli", text: "👍" },
{ time: "00:16:19", name: "Flaviane", text: "Alguem de Maceió??" },
{ time: "00:16:22", name: "Pietra", text: "Boa noite, começou agora?" },
{ time: "00:17:09", name: "Kesia", text: "Quero saber do abacate" },
{ time: "00:17:06", name: "Dani", text: "Virginia" },
{ time: "00:17:07", name: "simone", text: "Graianne e Virginia" },
{ time: "00:17:10", name: "Jane", text: "Virginia, Maira Cardi, Gracine" },
{ time: "00:17:12", name: "Lara", text: "Virginia" },
{ time: "00:17:14", name: "Manu", text: "Virginia" },
{ time: "00:17:20", name: "Zilda", text: "Interessante que saber, pode contar tudo" },
{ time: "00:18:57", name: "Meire", text: "Eu já fiz varios desafios e nunca emagreci" },
{ time: "00:18:58", name: "Dani", text: "Eu passo por todos esses problemas que você disse" },
{ time: "00:18:59", name: "Iara", text: "Já tomei muito remédio e nunca deu certo" },
{ time: "00:19:35", name: "Nubia", text: "Realmente as canetas são bem caras" },
{ time: "00:19:40", name: "Carla", text: "Eu estou choacada com isso" },
{ time: "00:19:46", name: "Odete", text: "comendo só um pouco engorda 3kg" },
{ time: "00:19:57", name: "Meire", text: "Tudo que já como... seria ótimo isso" },
{ time: "00:21:30", name: "Dani", text: "Nossa, eu engordo muito facil" },
{ time: "00:21:31", name: "Margareth", text: "Boa noite, filho." },
{ time: "00:23:27", name: "Iara", text: "Deeeus me livre" },
{ time: "00:23:28", name: "Sara", text: "Nem lembro quando usei um biquini" },
{ time: "00:23:29", name: "Isa", text: "Eu tenho uma luta para comprar roupa" },
{ time: "00:23:30", name: "Rafaela", text: "Balança não gosto não" },
{ time: "00:23:31", name: "Dani", text: "Estou tendo dificuldade demais, perciso de ajuda" },
{ time: "00:24:02", name: "Meire", text: "Nossa... só luz apagada no banho" },
{ time: "00:24:03", name: "Nubia", text: "Espelho não mente mesmo😔" },
{ time: "00:24:04", name: "Kesia", text: "Eu até podia ficar sem sair tem hora..." },
{ time: "00:24:05", name: "Odete", text: "Eu só compro roupa larga, malha fria, só elas par entrar" },
{ time: "00:25:36", name: "Renira", text: "eu sou assim" },
{ time: "00:25:38", name: "Zenia", text: "Falsa magra👍👍👍" },
{ time: "00:25:39", name: "Fatima", text: "Eu sou igual essa imagem, tenho a bananinha que me incomoda" },
{ time: "00:26:21", name: "Carla", text: "Não acredito, é você?" },
{ time: "00:26:22", name: "Maisa", text: "Ganhou tudo e mais um pouco😁😁😁" },
{ time: "00:26:23", name: "Katia", text: "Estou gostando de ver, parabéns pelo conteúdo. " },
{ time: "00:26:24", name: "Flores", text: "Hoje vai ser bom a aula!!" },
{ time: "00:26:55", name: "Fabia", text: "Sim verdade, regime deixa metabolismo lento" },
{ time: "00:26:56", name: "Neli", text: "Doce de noite é um perigo" },
{ time: "00:26:57", name: "Katiane", text: "Verdade" },
{ time: "00:26:58", name: "Maria Clara", text: "Eu tentei tomar mounjaro e acabei vendo que era bem caro😔" },
{ time: "00:27:35", name: "Juliana", text: "Eu faço jejum e quando chega de noite eu sempre sinto muita fome, e acabo pedindo um Ifood" },
{ time: "00:27:23", name: "Odete", text: "Eu acredito sim, faz total sentido" },
{ time: "00:27:23", name: "Nubia", text: "já ouvi falar de tudo!!" },
{ time: "00:27:23", name: "Jane", text: "Chega ser dificil de acreditar, mas faz sentido" },
{ time: "00:27:23", name: "Meire", text: "Isso é veradade, eu ja fiz kkkk" },
{ time: "00:27:52", name: "Isa", text: "Já usei Ozempic, e só dava conta de comer cois liqudia " },
{ time: "00:27:53", name: "Dani", text: "Mounjaro, mas n tenho dinheiro para usar" },
{ time: "00:27:53", name: "Rafaela", text: "Estou usando moujaro" },
{ time: "00:29:14", name: "Samanta", text: "Propósito" },
{ time: "00:29:05", name: "Kasia", text: "Parabéns Douglas, exemplo👍👍" },
{ time: "00:29:20", name: "Joelma", text: "eu tenho 35!" },
{ time: "00:29:21", name: "Neli", text: "62" },
{ time: "00:29:22", name: "Iara", text: "tenho 49" },
{ time: "00:29:23", name: "Mercia", text: "45" },
{ time: "00:29:24", name: "Ana", text: "53" },
{ time: "00:29:25", name: "Idiara", text: "37" },
{ time: "00:29:26", name: "Dani", text: "43" },
{ time: "00:29:27", name: "Rubia", text: "vou fazer 50" },
{ time: "00:29:32", name: "Fabia", text: "Eu acredito muito nisso" },
{ time: "00:29:33", name: "Layz", text: "Que história legal, parabéns Douglas" },
{ time: "00:29:34", name: "Zilda", text: "Eu confio" },
{ time: "00:29:37", name: "Deb", text: "O meu bloqueio tem intimidade com o meu propósito" },
{ time: "00:29:39", name: "Sara", text: "já sim, faz sentido" },
{ time: "00:30:11", name: "Renira", text: "Já tomei Naltrexona" },
{ time: "00:30:12", name: "Zenia", text: "Ozempic" },
{ time: "00:30:15", name: "Zenia", text: "Sibrutamina" },
{ time: "00:31:01", name: "Fabia", text: "Odeio academia, tem como emagrecer sem?" },
{ time: "00:31:24", name: "Pri", text: "Ele já falou do abacate??" },
{ time: "00:32:07", name: "Jucelina", text: "Eu conheço" },
{ time: "00:32:10", name: "Iracelma", text: "A fome vem forte, e ganha tudo de novo" },
{ time: "00:30:41", name: "Iara", text: "Eu tenho colesterol" },
{ time: "00:32:12", name: "Sara", text: "Eu já tomei..." },
{ time: "00:30:50", name: "Joelma", text: "Tenho diabete" },
{ time: "00:32:30", name: "Zilda", text: "Passou fome" },
{ time: "00:32:35", name: "Jucelina", text: "Coitadaa" },
{ time: "00:32:37", name: "Iracelma", text: "Minha nossa" },
{ time: "00:32:40", name: "Iara", text: "História complicada emm😔" },
{ time: "00:33:30", name: "Manu", text: "Calorias" },
{ time: "00:33:31", name: "Layz", text: "Comer menos, mas eu estou comendo tão pouco..." },
{ time: "00:33:36", name: "Dani", text: "Você tem que ajudar agende Douglas" },
{ time: "00:33:40", name: "Fabia", text: "Dificuldade de perder essa pochete" },
{ time: "00:33:41", name: "Neli", text: "Eu sou assim" },
{ time: "00:34:40", name: "Debora", text: "Faz sentido muito...😔" },
{ time: "00:34:42", name: "Layz", text: "Chocada" },
{ time: "00:35:05", name: "Kesia", text: "Faz sentido kkkk" },
{ time: "00:35:10", name: "Zilda", text: "Eu só como mato e não vejo perder peso também kkk" },
{ time: "00:35:30", name: "Renira", text: "Acredito muito nisso viu!" },
{ time: "00:35:35", name: "Dani", text: "Vivemos por aqui que acreditamos" },
{ time: "00:35:37", name: "Lays", text: "também sou assim" },
{ time: "00:35:40", name: "Fabia", text: "Eu acredito muito nisso" },
{ time: "00:35:41", name: "Layz", text: "já não aguento mais passar fome" },
{ time: "00:35:47", name: "Zilda", text: "Eu confio, vamos firmes meninas...." },
{ time: "00:36:39", name: "Debora", text: "O efeito sanfona é terrível, estou passando por isso agora" },
{ time: "00:36:39", name: "Sara", text: "já sim, faz sentido" },
{ time: "00:38:10", name: "Cassia", text: "Maiara" },
{ time: "00:38:11", name: "Elaine", text: "É aquela cantora" },
{ time: "00:38:15", name: "Lara", text: "Claro! Maira, emagreceu demais!!!" },
{ time: "00:38:20", name: "Josy", text: "Não fico bom não" },
{ time: "00:38:25", name: "Carla", text: "Eu não gosto assim" },
{ time: "00:38:53", name: "Jucelina", text: "Cara de doente" },
{ time: "00:39:46", name: "Maisa", text: "Meu instino é ruim mesmo, vou 2x na semana" },
{ time: "00:39:51", name: "Lud", text: "Proteina carboidrat e gordura" },
{ time: "00:39:52", name: "Katia", text: "Não quero emagrecer assim não" },
{ time: "00:39:53", name: "Flores", text: "kkkk" },
{ time: "00:39:57", name: "Meire", text: "Sim verdade" },
{ time: "00:39:59", name: "Elidiene", text: "Eu já fiz a dieta da proteína" },
{ time: "00:40:00", name: "Neli", text: "Sempre engordo tudo de novo" },
{ time: "00:40:00", name: "Katiane", text: "eu amo arroz, não do conta de ficar sem😔" },
{ time: "00:40:02", name: "Regina", text: "Da certo nada, se for assim prefiro desistir" },
{ time: "00:40:05", name: "Nubia", text: "Só ilusão essas dieta então👍👍" },
{ time: "00:40:06", name: "Irani", text: "Perdi 3kg e ganhei 6 depois" },
{ time: "00:40:10", name: "Renira", text: "sim" },
{ time: "00:40:10", name: "Dani", text: "Verdade viu" },
{ time: "00:40:11", name: "Mariana", text: "kkkk cabeça de ozempic primeira vez que escuto" },
{ time: "00:40:12", name: "Nayara", text: "Sim verdade" },
{ time: "00:41:30", name: "Zilda", text: "Essas canetas são muito caras" },
{ time: "00:41:36", name: "Jucelina", text: "Mais de mil reais" },
{ time: "00:41:37", name: "Fatima", text: "Comer menos, mas como fazer?" },
{ time: "00:41:40", name: "Iara", text: "Esse efeito rebote é grave, teve uma amiga que perdeu os movimentos das pernas" },
{ time: "00:41:41", name: "Manu", text: "Isso me desanima sabia..." },
{ time: "00:41:41", name: "Mercia", text: "Só eu comer menos, mas e a fome que eu fico no final do dia?" },
{ time: "00:41:45", name: "Dani", text: "verdade...." },
{ time: "00:41:46", name: "Jurere", text: "Começou agora meninas?" },
{ time: "00:42:02", name: "Iracelma", text: "Já tentei tudo isso que você falou kkkkk to gorda ainda" },
{ time: "00:42:12", name: "Manu", text: "Passo sempre por isso" },
{ time: "00:42:58", name: "Layz", text: "Ja tomei ozempic" },
{ time: "00:43:00", name: "Renira", text: "Já tomei Manipulado demais também" },
{ time: "00:43:05", name: "Zenia", text: "já ouvi falar" },
{ time: "00:43:08", name: "Zenia", text: "faz sentido o metabolismo fica lento" },
{ time: "00:43:20", name: "Kesia", text: "primeira semana vai 5kg facil facil, depois para" },
{ time: "00:43:21", name: "Laura", text: "eu sempre fiz assim, por isso não deu certo" },
{ time: "00:43:24", name: "Iara", text: "você vai audar agente a comer então???" },
{ time: "00:43:45", name: "Nubia", text: "Fome👍👍" },
{ time: "00:43:46", name: "Caleane", text: "Não faço nem ideia" },
{ time: "00:43:47", name: "Iara", text: "Realmente a fome me pega viu" },
{ time: "00:43:30", name: "Mercia", text: "não sei mais como fazer" },
{ time: "00:43:37", name: "Ana", text: "Calorias e controlar a fome, realmente faz sentido Douglas" },
{ time: "00:43:40", name: "Iara", text: "Não sei mesmo" },
{ time: "00:43:42", name: "Nubia", text: "compulsão eu já tive umas 5x" },
{ time: "00:43:43", name: "Kesia", text: "Então é por isso👍👍" },
{ time: "00:43:43", name: "Zilda", text: "Não faço ideia" },
{ time: "00:44:10", name: "Neli", text: "As canetas então não funciona??" },
{ time: "00:44:11", name: "Debora", text: "Ja tomei Saxenda, aplica todo dia né. passei mal demaaais credo" },
{ time: "00:44:16", name: "Layz", text: "Ozempic👍" },
{ time: "00:44:18", name: "Kesia", text: "Mas precisa de receita pra comprar..." },
{ time: "00:44:20", name: "Isa", text: "Realmente" },
{ time: "00:44:30", name: "Fabia", text: "Se deixar eu quero comer um boi" },
{ time: "00:44:52", name: "Katiane", text: "Doente, não ta legal" },
{ time: "00:44:53", name: "Angelina", text: "Ta desnutrida ela" },
{ time: "00:44:55", name: "Katianne", text: "Muito doente parece" },
{ time: "00:44:39", name: "Lara", text: "Da um prato de comida pra ela gente" },
{ time: "00:45:10", name: "simone", text: "Proteina resolve isso??" },
{ time: "00:45:00", name: "Iracelma", text: "foi bariatrica parece" },
{ time: "00:45:01", name: "Simone", text: "Ta com cara de doente" },
{ time: "00:45:05", name: "Ana Paula", text: "Coitada acabou com o corpo" },
{ time: "00:45:15", name: "Joelma", text: "Ela não ta bem!" },
{ time: "00:45:20", name: "Neli", text: "Que horror😖😖" },
{ time: "00:45:21", name: "Iara", text: "Meu intestino é péssimo, se eu tomar um trem desse eu morro" },
{ time: "00:45:30", name: "Mercia", text: "Já fiquei uma semana sem ir, meu máximo..." },
{ time: "00:45:31", name: "Ana", text: "Isso me deixa muito nervosa, sempre acabo tomando lactopurga" },
{ time: "00:46:12", name: "Rubia", text: "ta claro, e ta me deixando preocupada" },
{ time: "00:46:15", name: "Julia", text: "Verdade" },
{ time: "00:46:16", name: "Carla", text: "😖😖😖😖" },
{ time: "00:47:06", name: "Idiara", text: "entendo, eu passo por isso viu" },
{ time: "00:47:10", name: "Dani", text: "Verdade faz sentido" },
{ time: "00:47:20", name: "Lud", text: "Tenso" },
{ time: "00:47:21", name: "Cida", text: "Sim já ouvi isso" },
{ time: "00:49:06", name: "Neli", text: "boaaa kkkk" },
{ time: "00:50:04", name: "Iara", text: "Chegou a hora do abacate" },
{ time: "00:50:10", name: "Nubia", text: "Agora conta tudo pra gente" },
{ time: "00:50:11", name: "Kesia", text: "kkkk verdade viu" },
{ time: "00:50:16", name: "Zilda", text: "Agora eu quero até ver o que ele vai falar" },
{ time: "00:50:20", name: "Nubia", text: "É só comer abacate emagrece?" },
{ time: "00:51:08", name: "Josy", text: "O que tem o abacate gente?" },
{ time: "00:51:10", name: "Isa", text: "triptofano" },
{ time: "00:51:15", name: "Layz", text: "vou anotar para tomar depois" },
{ time: "00:51:20", name: "Zilda", text: "legal, gostei. Como chama mesmo?" },
{ time: "00:51:25", name: "Kesia", text: "Que legal não sabia" },
{ time: "00:51:30", name: "Jucelina", text: "isso vai me deixar sem fome, eu vou comer menos é isso?" },
{ time: "00:51:31", name: "Lara", text: "estou chocara" },
{ time: "00:52:16", name: "Kesia", text: "Que resultado legal, gostei" },
{ time: "00:52:20", name: "Layz", text: "Bloquear a gordura, já vi algo parecido" },
{ time: "00:52:21", name: "Renira", text: "que legal, eu percebo que meu coco fica com gordura no vaso" },
{ time: "00:52:22", name: "Zenia", text: "Você podia ajudar a gente" },
{ time: "00:52:27", name: "Zenia", text: "será que agora eu consigo emagrecer Douglas😭😭" },
{ time: "00:52:30", name: "Katianne", text: "econtr aonde esses produtos???" },
{ time: "00:53:43", name: "Iara", text: "Nunca ouv falar, onde compra" },
{ time: "00:53:44", name: "Mercia", text: "Psyllium mounjaro de pobre" },
{ time: "00:53:50", name: "Ana", text: "é ótimo eses eu já tomei" },
{ time: "00:54:28", name: "Marcia", text: "Eu tenho dificudlade de emagrecer " },
{ time: "00:54:30", name: "Lucia", text: "Não consigo perder nenhuma grama" },
{ time: "00:54:32", name: "Josy", text: "É até dificil de acreditar que faz tudo isso" },
{ time: "00:54:37", name: "Fabia", text: "é maravilhoso isso em" },
{ time: "00:54:40", name: "Layz", text: "Eu queria um produto assim" },
{ time: "00:55:06", name: "Iara", text: "Que legal essas substâncias, onde compra?" },
{ time: "00:55:10", name: "Mercia", text: "que lega" },
{ time: "00:56:11", name: "Flores", text: "Será que ele vai passar pra gente" },
{ time: "00:56:15", name: "Meire", text: "E quero fazer o acopanhamento com você!!!" },
{ time: "00:56:20", name: "Meire", text: "Essa é a fórmula do abacate então" },
{ time: "00:56:53", name: "Layane", text: "Que resultado maravilhoso, já quero" },
{ time: "00:56:56", name: "Jucelia", text: "perderam muito peso..." },
{ time: "00:56:59", name: "Luciana", text: "O que são macros?" },
{ time: "00:57:00", name: "Zenilda", text: "essas mulheres estão magras ainda depois de tomar?" },
{ time: "00:57:01", name: "flaviane", text: "Conheço só dois, vou procurar os outros" },
{ time: "00:57:05", name: "Debora", text: "Conheço a cafeína" },
{ time: "00:57:18", name: "Fabia", text: "Gostei, tem como repetir?" },
{ time: "00:57:20", name: "Meire", text: "Fabia, Proteina e Carboidrato e gordura" },
{ time: "00:58:35", name: "Iracelma", text: "Eu gosto de pescar" },
{ time: "00:58:38", name: "Margareth", text: "Estou aqui, firme filho" },
{ time: "00:58:39", name: "Isa", text: "para mim faz sentido agora" },
{ time: "00:58:40", name: "simone", text: "Legal, não sabia diso" },
{ time: "00:59:25", name: "Kesia", text: "Muito legal" },
{ time: "00:59:30", name: "Laura", text: "Parabéns" },
{ time: "00:59:39", name: "flaviane", text: "Aonde encontra?" },
{ time: "00:59:42", name: "Odete", text: "Que lega, também quero!" },
{ time: "00:59:50", name: "Rafaela", text: "adorei já quero" },
{ time: "01:00:01", name: "Luciana", text: "Meus parabéns" },
{ time: "01:00:05", name: "Angela", text: "Eu também quero" },
{ time: "01:00:10", name: "Rubia", text: "Realmente, faz todo sentido" },
{ time: "01:00:15", name: "Paula", text: "Que legal, parabéns Douglas" },
{ time: "01:00:20", name: "Kesia", text: "Muito legal" },
{ time: "01:00:22", name: "Laura", text: "Parabéns" },
{ time: "01:00:35", name: "Ana Clara", text: "Que top, meus parabéns" },
{ time: "01:00:40", name: "Iracelma", text: "Bora que quero mais, estou adorando..." },
{ time: "01:00:41", name: "Iara", text: "Show, vamos firme" },
{ time: "01:01:01", name: "Manu", text: "Triptofano que chama??" },
{ time: "01:01:02", name: "Luci", text: "Como escreve?" },
{ time: "01:01:20", name: "Iara", text: "Vamos lá!!!!!" },
{ time: "01:01:25", name: "Nubia", text: "Eu quero!" },
{ time: "01:01:29", name: "Manu", text: "Estamos preparadas" },
{ time: "01:01:30", name: "Pri", text: "Eu quero muito, estou precisando pra ontem" },
{ time: "01:01:35", name: "Angelina", text: "Vamos láaa👍👍👍" },
{ time: "01:01:36", name: "Katianne", text: "Eu quero" },
{ time: "01:01:40", name: "Lara", text: "Obaaa chegou!!" },
{ time: "01:01:43", name: "simone", text: "reset" },
{ time: "01:01:44", name: "Neli", text: "reset 👍👍👍" },
{ time: "01:01:45", name: "Iracelma", text: "vamos começar" },
{ time: "01:01:50", name: "Iara", text: "Conte comigo👍" },
{ time: "01:01:55", name: "Manu", text: "Tamo junto" },
{ time: "01:02:26", name: "Layz", text: "Reset" },
{ time: "01:02:30", name: "Iracelma", text: "Eu quero fazer." },
{ time: "01:02:31", name: "Iara", text: "como faz?" },
{ time: "01:02:40", name: "Manu", text: "Vai fazer pra gente Douglas??" },
{ time: "01:03:08", name: "Layz", text: "Eu quero esse remédio como faço??" },
{ time: "01:03:10", name: "Mercia", text: "compreendi" },
{ time: "01:03:15", name: "Marcia", text: "Só tem guerreira aqui hoje! Vamos lá meninas..." },
{ time: "01:03:52", name: "Ana", text: "já quero, gosto de produto natural" },
{ time: "01:04:00", name: "Lays", text: "manipulado da pra fazer então..." },
{ time: "01:04:01", name: "Zenilda", text: "todas suas pacientes usam então..." },
{ time: "01:04:05", name: "Flaviane", text: "👍👍 eu quero seu acompanhamento" },
{ time: "01:04:21", name: "Odete", text: "Você vai acompanhar a gente?!" },
{ time: "01:04:26", name: "Rafaela", text: "adorei já quero" },
{ time: "01:04:37", name: "Renira", text: "Eu gosto de Cafeína, é otimo, deve ser maravilhoso esse suplemento" },
{ time: "01:04:40", name: "Zenia", text: "é individual ou é grupo?" },
{ time: "01:04:41", name: "Fatima", text: "Você vai passar o que precisa fazer??" },
{ time: "01:04:46", name: "Lucia", text: "Adorei a combinação, parabéns Douglas" },
{ time: "01:04:50", name: "Josy", text: "Parabéns pelo programa, muito legal, como faz para começar?" },
{ time: "01:04:59", name: "Fabia", text: "Adorei, gostei demais." },
{ time: "01:05:40", name: "Iara", text: "Enfezada kkkk" },
{ time: "01:06:34", name: "Zenilda", text: "Eu preciso disso!" },
{ time: "01:06:35", name: "Katiane", text: "Perfeito!!!" },
{ time: "01:06:39", name: "Meire", text: "Eu quero Douglas, como faz?" },
{ time: "01:07:20", name: "Caleane", text: "10kg é um sonho" },
{ time: "01:07:30", name: "Maiza", text: "Perfeito, só do intestino funcionar eu acho ótimo" },
{ time: "01:07:40", name: "Debora", text: "eu tenho depressão desde quando engordei😭😭" },
{ time: "01:09:11", name: "Renira", text: "Meus parabéns, incrível" },
{ time: "01:09:15", name: "Pricila", text: "ahhhh... eu quero esse resultado" },
{ time: "01:09:20", name: "Meire", text: "Sim, concordo" },
{ time: "01:09:57", name: "Lud", text: "Eu já tinha ouvido falar sobre controlar as calorias, mas não sei como fazer" },
{ time: "01:10:00", name: "Cassia", text: "achei que era só cortar arroz..." },
{ time: "01:10:54", name: "Iara", text: "Ela deve ter uns 30 e poucos!!!!!" },
{ time: "01:10:55", name: "Nubia", text: "36!" },
{ time: "01:10:59", name: "Manu", text: "34" },
{ time: "01:11:40", name: "Pri", text: "Eu quero muito, estou precisando pra ontem" },
{ time: "01:11:45", name: "Angelina", text: "Vamos láaa, também quero👍👍👍" },
{ time: "01:11:46", name: "Katianne", text: "Eu quero" },
{ time: "01:11:47", name: "Lara", text: "Incrível esses resultados!!" },
{ time: "01:11:48", name: "simone", text: "reset" },
{ time: "01:11:50", name: "Neli", text: "reset 👍👍👍" },
{ time: "01:12:15", name: "Iracelma", text: "vamos começar" },
{ time: "01:12:20", name: "Iara", text: "Bora começar👍" },
{ time: "01:12:21", name: "Manu", text: "Tamo junto" },
{ time: "01:12:30", name: "🤖SUPORTE", text: "AGUARDEM MENINAS!!!" },
{ time: "01:13:30", name: "Jucelina", text: "isso vai me deixar sem fome, eu quero" },
{ time: "01:13:35", name: "Lara", text: "como faz, eu quero??" },
{ time: "01:13:40", name: "Kesia", text: "aonde compra???" },
{ time: "01:13:45", name: "Layz", text: "vai liberar pra nós Douglas" },
{ time: "01:13:50", name: "Renira", text: "que legal, eu quero" },
{ time: "01:13:55", name: "Zenia", text: "aceita cartão???/" },
{ time: "01:14:13", name: "Isa", text: "Eu quero o Triptoplus" },
{ time: "01:14:15", name: "Rafaela", text: "adorei já quero" },
{ time: "01:14:19", name: "Isa", text: "Eu quero" },
{ time: "01:15:01", name: "Iara", text: "Quero começar hoje" },
{ time: "01:15:13", name: "Manu", text: "eu preciso perder 25kg, vou comprar" },
{ time: "01:15:25", name: "Layz", text: "12 meses eu consigo ficar do jeito que eu quero, com sua ajuda" },
{ time: "01:15:37", name: "Mercia", text: "compreendi" },
{ time: "01:16:18", name: "Flores", text: "Vamos lá!" },
{ time: "01:16:28", name: "Luciana", text: "Eu quero fazer o RESET" },
{ time: "01:16:38", name: "simone", text: "Já quero Douglas" },
{ time: "01:16:40", name: "Iracelma", text: "vamos começar" },
{ time: "01:17:02", name: "Katianne", text: "Olha... já tentei tanto, agora não é possível😔😔" },
{ time: "01:17:05", name: "Lara", text: "Ai que sonho" },
{ time: "01:17:34", name: "Maria", text: "Sim, é ótimo todo suporte que você dá!" },
{ time: "01:17:39", name: "Natanna", text: "Esse atendimento humanizado, mais de perto... isso me da muita confiança" },
{ time: "01:18:20", name: "Ana Paula", text: "Melhor investimento que já fiz, obrigada Douglas" },
{ time: "01:18:39", name: "Nathalia", text: "To aqui, firme forte, obrigada por tudo Douglas!" },
{ time: "01:18:47", name: "Isa", text: "Nosssa Muito barato" },
{ time: "01:18:50", name: "Josy", text: "Eu quero!!!" },
{ time: "01:19:12", name: "Juventite", text: "Quero, como faz para comprar?" },
{ time: "01:19:23", name: "Juliana", text: "Eu também quero" },
{ time: "01:19:33", name: "Maria", text: "Obrigado por tudo Douglas, estou adorando os resultados!!!" },
{ time: "01:20:09", name: "Laura", text: "Aprendi muita coisa nova" },
{ time: "01:20:14", name: "Manu", text: "Conhecimento é libertador mesmo" },
{ time: "01:20:19", name: "Katia", text: "Parabéns Douglas, por entregar tanto...." },
{ time: "01:20:20", name: "Angelina", text: "Eu só conhecia as dietas kkkk mas não sabia por que dava errado" },
{ time: "01:20:22", name: "Nubia", text: "Eu quero um resultado deste!!" },
{ time: "01:20:25", name: "Kesia", text: "Que lindas" },
{ time: "01:20:30", name: "Zilda", text: "Adorei, quero começar também" },
{ time: "01:20:31", name: "Pri", text: "Parabéns para vocês meninas, que conseguiram, ficaram muito bonitas" },
{ time: "01:20:40", name: "Jucelia", text: "A próxima será eu!!!😃😃" },
{ time: "01:20:45", name: "Zenilda", text: "Realmente não tem como ter desculpa, muito barato" },
{ time: "01:20:46", name: "flaviane", text: "Quero começar com esse desconto" },
{ time: "01:21:35", name: "Nubia", text: "Eu entrei" },
{ time: "01:21:36", name: "🤖SUPORTE", text: "VAGAS LIMITADAS: https://sun.eduzz.com/fruewagh?cupom=OFF100" },
{ time: "01:21:39", name: "Ana Paula", text: "Quero começar, o que devo fazer depois que contratar" },
{ time: "01:22:11", name: "Julia", text: "Vou tomar cedo e de tarde para ter mais resultado kkkkk" },
{ time: "01:22:14", name: "Flores", text: "Vamos lá!" },
{ time: "01:22:15", name: "Luciana", text: "Eu quero fazer o RESET" },
{ time: "01:22:20", name: "Sara", text: "Realmente eu já tentei muita coisa." },
{ time: "01:22:21", name: "Isa", text: "nooossa o que já gastei não ta escrito" },
{ time: "01:23:41", name: "Rafaela", text: "Verdade, eu topo essa chance" },
{ time: "01:23:53", name: "Dani", text: "Fiz tratamento com ozempic gastei quase 10mil e não ficou da forma como eu queria." },
{ time: "01:24:17", name: "Isa", text: "Nosssa Muito barato" },
{ time: "01:24:20", name: "Thais Santos", text: "Eu já garanti com o desconto!!!" },
{ time: "01:25:22", name: "Fernanda", text: "To dentro, aproveitar o desconto..." },
{ time: "01:25:33", name: "Maria Inês", text: "Eu entrei" },
{ time: "01:26:28", name: "Mercia", text: "Nossa muito barato mesmo" },
{ time: "01:26:36", name: "Fabia", text: "Separa o meu Douglas👍👍👍" },
{ time: "01:26:57", name: "🤖SUPORTE", text: "R$ 100 DESCONTO: https://sun.eduzz.com/fruewagh?cupom=OFF100" },
{ time: "01:26:39", name: "Angelina", text: "Posso pegar contigo no consultório??" },
{ time: "01:26:40", name: "Katianne", text: "Quero começar hj, pode??😃😃" },
{ time: "01:26:43", name: "Angela", text: "Tudo ok, vamos começar" },
{ time: "01:26:45", name: "Iracelma", text: "Combinado" },
{ time: "01:27:24", name: "Iara", text: "Eu topo!!!" },
{ time: "01:27:26", name: "Manu", text: "Quero começar" },
{ time: "01:27:30", name: "Iracelma", text: "Pode começar amanhã, oba!!!" },
{ time: "01:27:31", name: "Iara", text: "Já garanti o meu!!! ihuullll" },
{ time: "01:27:36", name: "Odete", text: "Acabei de entrar!" },
{ time: "01:27:40", name: "Laura", text: "Top eu quero, 30 dias de garantia" },
{ time: "01:28:09", name: "Lara", text: "Eu consegui adquirir com o desconto de R$ 100,00!!!" },
{ time: "01:28:37", name: "Josi", text: "Realmente ta bem barato" },
{ time: "01:29:38", name: "Manu", text: "Entrei, e agora Douglas???" },
{ time: "01:29:40", name: "Marcia", text: "E topo, vou entrar agora!!!" },
{ time: "01:29:20", name: "Raquel", text: "Após o pagamento o que devo fazer?" },
{ time: "01:29:51", name: "Juliana", text: "Como é a forma de pagamento?" },
{ time: "01:29:57", name: "🤖SUPORTE", text: "ESGOTANDO: https://sun.eduzz.com/fruewagh?cupom=OFF100" },
{ time: "01:30:20", name: "Marcia S.", text: "Consegue segurar até quinta?" },
{ time: "01:30:25", name: "Jucelina", text: "Vai até que dia mesmo?" },
{ time: "01:30:30", name: "Carla", text: "Meu marido pode tomar também?" },
{ time: "01:30:45", name: "Jane", text: "Em quanto tempo eu vou receber o suplemento?" },
{ time: "01:30:48", name: "Meire", text: "VIXXXXX😔" },
{ time: "01:30:50", name: "Meire", text: "Posso dar para meu filho?" },
{ time: "01:30:55", name: "Lay", text: "É verdade" },
{ time: "01:30:59", name: "Rosa", text: "Moro no interior, como eu faço?" },
{ time: "01:31:30", name: "Natalia", text: "Aceita pagamento via boleto?" },
{ time: "01:31:35", name: "Rosana", text: "Tomo remédio para pressão, posso tomar o Triptoplus?" },
{ time: "01:31:42", name: "🤖SUPORTE", text: "GARANTA SUA VAGA: https://sun.eduzz.com/fruewagh?cupom=OFF100" },
{ time: "01:31:43", name: "🤖SUPORTE", text: "Restam 17 vagas para bater os 30 acessos!" },
{ time: "01:31:49", name: "Marcia", text: "Tem alguma contraindicação???" },
{ time: "01:32:05", name: "Maisa", text: "Posso comprar para minha amiga também?" },
{ time: "01:32:15", name: "Iracelma", text: "O melhor plano é o que eu consigo seguir!!!" },
{ time: "01:32:19", name: "Rosana", text: "Eu tomo remédio para pressão, eu posso tomar?" },
{ time: "01:32:30", name: "Silvia Carlos", text: "Você falou que eu ia perder 12kg e eu já perdi 16, o que eu faço agora?" },
{ time: "01:32:57", name: "🤖SUPORTE", text: "ÚLTIMAS VAGAS: https://sun.eduzz.com/fruewagh?cupom=OFF100" },
{ time: "01:33:00", name: "Simone", text: "Adorei demais!!!" },
{ time: "01:33:28", name: "🤖SUPORTE", text: "Apenas 1 vaga com o desconto de R$ 100,00" },
{ time: "01:33:30", name: "Daiane", text: "Você é médico?" },
{ time: "01:33:36", name: "Angelica", text: "Sim, faz sentido" },
{ time: "01:33:45", name: "Luciana", text: "A garantia me fez ter confiança!!! Já entrei" },
{ time: "01:33:50", name: "Jurema", text: "Realmente, não tenho mais tempo para ficar perdendo..." },
{ time: "01:34:04", name: "🤖SUPORTE", text: "Instagram: @doug.leao" },
{ time: "01:34:01", name: "Samanta", text: "E se eu não conseguir seguir?" },
{ time: "01:34:45", name: "Zenilda", text: "Realmente eu faço isso😔😔" },
{ time: "01:34:48", name: "Simone", text: "eu perciso de ajuda, vou entrar!!!" },
{ time: "01:34:59", name: "Mariana", text: "Como eu vou receber os acessos?" },
{ time: "01:35:00", name: "Kesia", text: "Acabei de adquirir, obrigada Douglas e a equipe já recebi mensagem" },
{ time: "01:35:30", name: "Laura", text: "Alguém aqui conseguiu o desconto de 100?" },
{ time: "01:35:36", name: "Iara", text: "Alguem aqui comprou?? A página não esta abrindo mais..." },
{ time: "01:35:56", name: "🤖SUPORTE", text: "12 MESES: https://sun.eduzz.com/fruewagh?cupom=OFF100" },
{ time: "01:35:56", name: "Simone", text: "Parabéns!!!" },
{ time: "01:35:57", name: "🤖SUPORTE", text: "12 VAGAS" },
{ time: "01:36:40", name: "Mercia", text: "Tá vou te chamar no privado para tirar algumas dúvidas..." },
{ time: "01:36:50", name: "Manu", text: "Muito obrigada, foi sensacional" },
{ time: "01:37:00", name: "Layz", text: "Gostei muito, adorei" },
{ time: "01:37:02", name: "Dani", text: "Parabéns Douglas, belíssimo trabalho" },
{ time: "01:37:10", name: "🤖SUPORTE", text: "RESET Metabólico: 12 MESES: https://sun.eduzz.com/fruewagh?cupom=OFF100" },
{ time: "01:37:15", name: "Fabia", text: "Que linda!!" },
{ time: "01:37:40", name: "Neli", text: "Já entrei, vou começar amanhã" },
{ time: "01:37:44", name: "Debora", text: "Boa meninas!!" },
{ time: "01:39:49", name: "Ana Paula", text: "Ainda tem o deconto??" },
{ time: "01:39:59", name: "Maria Clara", text: "Será que a equipe vai enviar novamente o link ou esgotou?" },
{ time: "01:40:00", name: "Layz", text: "Ja tomei ozempic" },
{ time: "01:40:05", name: "Renira", text: "Já tomei tanta coisa, essa é a última que vou tentar.🙏🙏" },
{ time: "01:40:30", name: "Zenia", text: "Ozempic" },
{ time: "01:40:31", name: "Zenia", text: "Detox, e nunca tive resultado" },
{ time: "01:40:40", name: "🤖SUPORTE", text: "Ainda restam algunas vagas meninas, corre que da tempo!!" },
{ time: "01:41:05", name: "Katianne", text: "Olha... ninguem nunca me ensino isso😔😔" },
{ time: "01:41:15", name: "🤖SUPORTE", text: "ÚLTIMAS VAGAS" },
{ time: "01:41:16", name: "🤖SUPORTE", text: "corre: https://sun.eduzz.com/fruewagh?cupom=OFF100" },
{ time: "01:41:20", name: "Katia", text: "Parabéns Douglas, por entregar tanto...." },
{ time: "01:41:30", name: "Angelina", text: "Eu só conhecia as dietas kkkk mas não sabia porque dava errado" },
{ time: "01:41:34", name: "Lara", text: "Ai que sonho" },
{ time: "01:41:40", name: "Nubia", text: "Eu quero um resultado deste!!" },
{ time: "01:41:50", name: "Kesia", text: "Que linda" },
{ time: "01:42:00", name: "Zilda", text: "Adorei, quero começar também" },
{ time: "01:42:14", name: "🤖SUPORTE", text: "ENCERRANDO EM BREVE...🏃" },
{ time: "01:42:20", name: "Pri", text: "Parabéns para vocês que conseguiram, ficaram muito bonitas" },
{ time: "01:42:22", name: "🤖SUPORTE", text: "ÚLTIMA VAGA: https://sun.eduzz.com/fruewagh?cupom=OFF100" },
{ time: "01:42:42", name: "Jucelia", text: "A próxima será eu!!!😃😃" },
{ time: "01:42:49", name: "Zenilda", text: "Realmente não tem como ter desculpa" },
{ time: "01:42:50", name: "Zilda", text: "Quem ai conseguiu comprar? Não esta abrindo aqui pra mim" },
{ time: "01:44:00", name: "Pri", text: "Parabéns para vocês, lindas" },
{ time: "01:44:10", name: "Jucelia", text: "Boa noite, obrigado meninas" },
{ time: "01:44:15", name: "🤖SUPORTE", text: "Encerrando transmissão em 15 segundos!" }

		
    ];
