
window.messages = [
  "Gente, alguém mais sente que já tentou de tudo e nada funcionou? 😭",
  "Meu maior medo sempre foi esse efeito sanfona, mas nunca ouvi explicarem desse jeito...",
  "Essa parte do carboidrato me deu um nó na cabeça, sempre achei que era o vilão.",
  "Tô chocada! Sempre achei que o problema era eu...",
  "Alguém aqui já fez Ozempic e voltou a engordar depois? Achei que era só comigo...",
  "Preciso mostrar esse vídeo pra minha irmã, ela sofre tanto com essas dietas malucas.",
  "Parece que tá falando diretamente comigo 😳",
  "Eu jurava que jejum era o único jeito, mas nunca consegui manter por muito tempo.",
  "Minhas amigas precisam ver isso, sério.",
  "Nunca vi explicarem metabolismo de um jeito tão claro, tô boba.",
  "Alguém aí já ouviu falar desse tal triptofano?",
  "Sempre tive vergonha do meu corpo, até de tomar banho com a luz acesa...",
  "Tô começando a entender porque sempre engordei tudo de novo.",
  "O negócio é que todo mês eu recomeço uma dieta diferente, cansa demais.",
  "Se isso tudo for verdade, vou indicar pra todo mundo!",
  "Caramba, então não era falta de força de vontade?",
  "Sempre fui aquela que come pouco e não emagrece, agora tô entendendo porque.",
  "Minha mãe gastou uma fortuna nessas canetinhas e só piorou.",
  "Nunca ouvi falar desse ativo natural na banana, tô curiosa.",
  "Alguém sabe se pode usar isso junto com remédio controlado?",
  "A parte do chocolate me deu esperança! Sempre achei que nunca mais poderia comer.",
  "Meu marido acha que dieta é só fechar a boca, ele precisa ouvir isso.",
  "Eu já fiz todas essas dietas de blogueira, é tudo igual mesmo!",
  "Meu maior sonho é vestir uma roupa sem medo do espelho.",
  "Será que esse protocolo serve pra quem tem mais de 40 anos?",
  "Alguém aí já conseguiu emagrecer sem passar fome?",
  "Tô anotando tudo! Nunca vi tanta informação de verdade.",
  "Adorei quando falou da comparação com animais, nunca tinha pensado nisso.",
  "Já tava quase comprando outro suplemento, mas vou esperar terminar o vídeo.",
  "A ansiedade só aumentava depois de cada dieta... faz sentido demais isso.",
  "Alguém sabe se isso serve pra quem tem hipotireoidismo?",
  "Se tudo isso funcionar mesmo, vai ser um milagre na minha vida.",
  "Eu nunca comento, mas hoje senti que precisava.",
  "A parte da compulsão por doce é minha maior dificuldade.",
  "Nunca ouvi ninguém falar a verdade sobre os rebotes das dietas.",
  "Se der certo, vou indicar pra minha mãe e minhas amigas.",
  "Como será que é essa consultoria individual? Fiquei curiosa.",
  "Já quero essas receitas que falou nos bônus!",
  "Quero muito ver antes e depois das alunas.",
  "Minha filha tá assistindo comigo, também sofre muito com o peso.",
  "Sempre ouvi falar mal do pão, agora tô com esperança.",
  "Eu já tomei remédio pra emagrecer e só piorei, alguém mais?",
  "Preciso dessa solução pra ontem.",
  "A explicação sobre as blogueiras foi cirúrgica! Sempre desconfiei.",
  "Tô sentindo que agora vai!",
  "Nunca vi um acompanhamento tão próximo assim, parece que é de verdade.",
  "Eu quero ser a próxima história de sucesso desse protocolo.",
  "Já fiquei com vontade de experimentar só pela energia desse vídeo.",
  "Se resolver minha fome à noite, já vale tudo.",
  "Nunca imaginei que o segredo estivesse numa fruta tão comum.",
  "Esse vídeo apareceu pra mim na hora certa.",
  "Alguém mais sentiu vontade de chorar ouvindo a história do garoto?",
  "A parte da calça na loja doeu na alma, já passei por isso.",
  "Parece que finalmente entendi porque sempre fracassei.",
  "Meu marido já não acredita em mais nada, vou mostrar pra ele também.",
  "Sempre tive vergonha de praia, será que um dia isso passa?",
  "Já ouvi prometerem mil coisas, mas aqui sinto verdade.",
  "Será que serve pra quem já passou dos 50?",
  "Essa coisa de rebote me pegou, nunca mais quero passar por isso.",
  "Tô esperando só a hora da oferta pra pegar minha vaga.",
  "A energia desse chat tá surreal, parece que tá todo mundo na mesma luta.",
  "Quero ver depoimentos de quem já fez!",
  "É a primeira vez que vejo nutricionista falando dos bastidores assim.",
  "Alguém aí já conseguiu manter o peso depois de emagrecer?",
  "A história da infância é muito parecida com a minha.",
  "Tô com medo de ser mais uma ilusão, mas quero tentar.",
  "O vídeo me fez pensar em tudo que já gastei tentando emagrecer.",
  "Meu sonho é comprar uma calça menor sem sofrer.",
  "Já indiquei o vídeo pra minha irmã, ela também precisa.",
  "Alguém aí já começou o protocolo e pode contar como foi?",
  "A parte do tripé me chamou muita atenção.",
  "Será que entrega pra interior também?",
  "Estou emocionada com o que ouvi, nunca vi falarem assim.",
  "Nunca acreditei nessas fórmulas mágicas, mas parece diferente.",
  "É bom saber que tem acompanhamento, já me perdi tantas vezes.",
  "O que mais gostei foi que não precisa cortar tudo.",
  "Aquela história da blogueira me fez abrir os olhos.",
  "Preciso dessa transformação na minha vida.",
  "É difícil confiar depois de tanta decepção, mas vou tentar.",
  "Esse bônus das receitas é tudo pra mim!",
  "Nunca consegui emagrecer sem sofrer, será que dessa vez vai?",
  "Já marquei minha amiga nos comentários pra assistir junto.",
  "Tenho medo de gastar dinheiro e me frustrar de novo.",
  "Se for tudo isso que falou, vou ser eternamente grata.",
  "A parte da serotonina me interessou muito, tenho ansiedade.",
  "Já anotei todos os ingredientes, quero testar.",
  "Nunca vi alguém explicar o metabolismo desse jeito.",
  "Minha irmã já fez de tudo e nada deu certo, vou mostrar pra ela.",
  "Alguém aí também sente compulsão por doce à noite?",
  "Vi que tem bônus de grupo, quero participar.",
  "É difícil encontrar médico que fale a verdade assim.",
  "Minha autoestima está no chão, mas fiquei esperançosa.",
  "Nunca consegui passar de 3 semanas em dieta.",
  "Já testei todas essas canetinhas, nenhuma funcionou de verdade.",
  "Quero ver depoimentos de quem já terminou o protocolo.",
  "Alguém sabe se tem garantia de verdade?",
  "Essa live foi um presente pra mim hoje.",
  "Parece que foi feito sob medida pra mim.",
  "Tô sentindo que dessa vez vai ser diferente.",
  "Nunca vi explicação tão completa e humana.",
  "A vontade de mudar só aumentou vendo tudo isso.",
  "A parte do triptofano me surpreendeu demais.",
  "Sempre achei que só sofrendo dava resultado.",
  "Já tentei de tudo, só falta acreditar em mim mesma.",
  "Será que alguém já perdeu mais de 10kg com esse método?",
  "Quero participar desse grupo de apoio urgente!",
  "Preciso aprender a manter o peso, nunca consegui.",
  "Já indiquei o vídeo pra minha mãe e minha tia.",
  "Quero saber se tem acompanhamento depois das 6 semanas.",
  "Tem alguém aí que já está fazendo e quer compartilhar resultado?",
  "Nunca ouvi falar de psyllium, onde compra?",
  "Acho que agora entendi onde estava errando.",
  "Ver todo mundo comentando aqui dá força pra continuar.",
  "Minha maior dificuldade sempre foi comer pouco e não emagrecer.",
  "Espero não perder minha vaga, quero muito tentar.",
  "Já deixei o like só pelo conteúdo!",
  "É agora ou nunca, tô pronta pra mudar.",
  "Alguém aí conhece alguém que já fez o protocolo?",
  "Tô pensando em começar amanhã mesmo.",
  "Sempre ouço falarem mal de carboidrato, mas agora faz sentido.",
  "Esse vídeo é tipo um divisor de águas na minha vida.",
  "Nunca vi live tão interativa, parece que lê meus pensamentos.",
  "Espero conseguir manter o resultado dessa vez.",
  "Fiquei chocada com o preço das canetinhas, é absurdo.",
  "Quero aprender a comer de tudo sem culpa.",
  "Tô ansiosa pra saber mais sobre a Fórmula do Abacate.",
  "Nunca pensei que daria pra emagrecer sem passar fome.",
  "Já comecei a seguir o Douglas no Insta!",
  "Tô apaixonada pela proposta, quero ser case de sucesso.",
  "Quero transformar minha história igual a da Marina.",
  "Nunca consegui emagrecer e manter, será que agora vai?",
  "Tô quase chorando aqui, me identifiquei demais.",
  "Amei o jeito simples de explicar, sem enrolação.",
  "Quero que minha filha veja esse vídeo, ela sofre demais com peso.",
  "A parte do acompanhamento semanal faz toda diferença.",
  "Já tô planejando minha alimentação pra começar.",
  "Faz sentido demais isso de não ser culpa nossa.",
  "Nunca imaginei que minha vida mudaria num vídeo.",
  "Se conseguir perder 5kg já tô feliz!",
  "Vou indicar pra minha nutricionista assistir também.",
  "Amei saber que tem garantia, isso dá segurança.",
  "Tô curiosa pra saber se alguém aí já conseguiu emagrecer comendo chocolate.",
  "Amei a energia dessa comunidade, não me sinto sozinha.",
  "Fazia tempo que não me sentia motivada assim.",
  "Nunca acreditei em resultados rápidos, mas agora entendi o porquê.",
  "Quero muito mudar minha relação com a comida.",
  "Tô cansada de sofrer calada, quero tentar de novo.",
  "Sempre achei que precisava comer menos, nunca pensei no metabolismo.",
  "Essa explicação do corpo magro comendo de tudo foi libertadora.",
  "Já compartilhei o link com o grupo da família.",
  "A história da loja foi um tapa na cara, já vivi isso.",
  "Me emocionei com o relato das clientes.",
  "Nunca vi um profissional assumir tanto compromisso.",
  "Já quero garantir minha vaga antes que acabe.",
  "É libertador ouvir que não é preciso cortar tudo.",
  "Se funcionar, vai ser a melhor coisa da minha vida.",
  "Tô decidida a tentar mais uma vez.",
  "Alguém aí já pediu a Fórmula do Abacate?",
  "Amei saber que o acompanhamento é de verdade.",
  "Espero que minha história esteja aqui no final também.",
  "Nunca comentei antes, mas hoje precisava.",
  "Meu maior desejo é vestir biquíni sem vergonha.",
  "A explicação do efeito sanfona foi perfeita.",
  "Alguém sabe se pode tomar junto com academia?",
  "Já compartilhei no grupo das amigas, elas precisam ver.",
  "Se eu conseguir emagrecer, vou contar pra todo mundo.",
  "Preciso perder peso pra saúde, não só estética.",
  "Essa live tá abrindo minha mente pra muita coisa.",
  "Já adicionei o número no WhatsApp pra tirar dúvidas.",
  "Nunca vi bônus tão úteis em uma oferta.",
  "Se eu não conseguir dessa vez, desisto de tentar.",
  "Amei a sinceridade, sem prometer milagre.",
  "Alguém já recebeu a fórmula em casa? Demorou muito?",
  "Quero ver fotos de antes e depois pra me motivar.",
  "A parte do controle da fome faz muito sentido pra mim.",
  "Sempre me culpei por não conseguir, agora vejo que não era só eu.",
  "Meu maior desejo é manter o peso sem sofrimento.",
  "Tô decidida a pegar essa vaga hoje!",
  "Quero perder peso, mas sem abrir mão do arroz e feijão.",
  "A explicação científica foi sensacional, nunca vi igual.",
  "Já indiquei pra minha colega do trabalho.",
  "Meu maior problema é beliscar o dia inteiro.",
  "Quero aprender a não sentir culpa depois de comer.",
  "Se o grupo de apoio ajudar mesmo, vai ser demais.",
  "Minha mãe ficou animada também, vamos tentar juntas.",
  "Fiquei emocionada com a parte do sofrimento na infância.",
  "Espero que tenha vaga pra mim ainda.",
  "Meu maior medo sempre foi engordar tudo de novo.",
  "Nunca vi alguém garantir tanto resultado.",
  "Já quero esse protocolo pra ontem!",
  "Fiquei surpresa com a sinceridade sobre as canetinhas.",
  "Quero ver se tem relatos de quem perdeu 10kg ou mais.",
  "Minha maior dificuldade é manter o foco, o grupo pode ajudar?",
  "Sempre achei que tinha que sofrer pra emagrecer.",
  "A explicação sobre a serotonina abriu minha mente.",
  "Já compartilhei esse vídeo no status do WhatsApp.",
  "Quero ser a próxima transformação a aparecer aqui.",
  "Nunca consegui emagrecer sem engordar de novo.",
  "Me emocionei com a história do garoto, já vivi isso.",
  "Se for mesmo como falou, é minha última tentativa.",
  "Nunca pensei que encontraria esperança num vídeo.",
  "Já tentei várias vezes e fracassei, mas quero tentar de novo.",
  "Quero saber se tem alguém aqui com mais de 50 anos que conseguiu.",
  "Amei saber que pode comer de tudo, nunca gostei de restrição.",
  "Tô pronta pra transformar minha vida.",
  "Se funcionar, prometo indicar pra todo mundo!",
  "Nunca vi tanta mulher unida pelo mesmo objetivo.",
  "A parte do acompanhamento individual me passou confiança.",
  "Já cansei de tentar sozinha, quero ajuda de verdade.",
  "Meu maior sonho é parar de fugir das fotos.",
  "Se resolver minha compulsão, já fico feliz.",
  "Nunca vi um chat tão animado e cheio de vida.",
  "A parte da ciência me convenceu, agora quero testar.",
  "Quero ser inspiração pra outras mulheres também.",
  "Tô torcendo pra garantir minha vaga ainda hoje.",
  "Se der certo comigo, vai ser um milagre.",
  "Já tô esperando o link pra fazer minha inscrição.",
  "Nunca vi tanta verdade junta numa live só.",
  "O conteúdo tá de graça, nunca vi igual.",
  "Já tô compartilhando com todo mundo!",
  "A energia aqui tá surreal, obrigada Douglas.",
  "Nunca imaginei que fosse possível emagrecer desse jeito.",
  "Quero ver como é o manual que vem junto.",
  "Já tô dentro, agora é só esperar o resultado.",
  "Se eu conseguir, vou tirar muita foto de antes e depois.",
  "Já cansei de sofrer, agora vai!",
  "Nunca vi uma explicação tão clara sobre efeito sanfona.",
  "O protocolo parece ser tudo o que eu precisava.",
  "Se der certo, nunca mais faço outra dieta maluca.",
  "A explicação sobre comer de tudo me surpreendeu.",
  "Tô sentindo uma esperança que não sentia há anos.",
  "Espero que meu depoimento apareça aqui um dia.",
  "Meu maior medo sempre foi não conseguir, mas agora quero tentar.",
  "Amei saber que é tudo natural, não gosto de remédio forte.",
  "Já chamei no WhatsApp pra saber mais.",
  "Quero experimentar pra ver se é isso tudo mesmo.",
  "Se eu conseguir mudar, vou ser a maior fã!",
  "Nunca imaginei que um vídeo mudaria tanto minha perspectiva.",
  "Já indiquei pra minha nutricionista assistir.",
  "A explicação sobre proteína fez total sentido pra mim.",
  "Se conseguir perder 6kg já fico feliz.",
  "Meu maior problema sempre foi desistir no meio do caminho.",
  "Se eu conseguir manter depois, já vale tudo.",
  "Quero aprender a comer certo, sem sofrimento.",
  "Nunca vi nutricionista falar tão abertamente dos bastidores.",
  "Amei a energia desse grupo, não me sinto sozinha.",
  "O bônus do grupo VIP vai me ajudar a não desistir.",
  "Já chamei minha mãe pra assistir junto.",
  "Espero conseguir chegar ao meu objetivo dessa vez.",
  "Nunca vi tanta gente animada ao mesmo tempo.",
  "A parte da garantia me deixou tranquila pra tentar.",
  "Já quero começar hoje mesmo!",
  "Quero mudar minha vida, chega de sofrer com peso.",
  "Se funcionar, nunca mais faço dieta maluca.",
  "Amei saber que não precisa de ingredientes caros.",
  "Já cansei de gastar dinheiro à toa, espero que aqui seja diferente.",
  "A explicação sobre os pilares me convenceu.",
  "Se conseguir resultado, vou postar meu antes e depois.",
  "Nunca vi tanta mulher unida por uma causa só.",
  "Amei saber que tem consultoria individual.",
  "Já tô sonhando com o dia de vestir o biquíni sem medo.",
  "Quero muito essa transformação na minha vida.",
  "Nunca pensei que um protocolo pudesse ser tão completo.",
  "Já mandei mensagem pra tirar dúvida, tô ansiosa.",
  "Se eu conseguir, prometo indicar pra toda minha família.",
  "O grupo de apoio parece incrível, quero participar.",
  "Já compartilhei com minhas amigas, elas precisam ver.",
  "Nunca vi nutricionista tão humano e próximo.",
  "Já tô dentro, agora é só aguardar meu kit chegar.",
  "Amei o bônus das receitas práticas.",
  "Espero conseguir me manter focada dessa vez.",
  "Se funcionar, vou ser depoimento aqui também.",
  "Nunca vi live tão interativa e acolhedora.",
  "Tô sentindo uma energia boa aqui, acho que agora vai.",
  "Quero perder peso sem perder saúde, esse protocolo parece perfeito.",
  "Já indiquei pra três amigas só hoje!",
  "A explicação sobre massa muscular fez todo sentido.",
  "Se eu conseguir, vou contar minha história pra inspirar outras mulheres.",
  "Quero ser a próxima história de sucesso desse método.",
  "Nunca imaginei que fosse possível comer chocolate e emagrecer.",
  "Já perdi as contas de quantas dietas já tentei.",
  "Agora vou até o fim, não desisto mais!",
  "Se eu conseguir mudar minha vida, vai ser graças a esse vídeo.",
  "Amei saber que é aprovado pela ANVISA.",
  "Nunca vi alguém garantir tanto resultado assim.",
  "Já tô pronta pra mudar, só falta clicar no botão.",
  "Se eu conseguir, vai ser o melhor investimento da minha vida.",
  "Quero aprender a me alimentar melhor, sem terrorismo nutricional.",
  "Já tô dentro, agora é só esperar o acompanhamento começar.",
  "Amei a energia do Douglas, passa confiança.",
  "Se funcionar pra mim, vai funcionar pra todo mundo.",
  "Já compartilhei o link com minha família.",
  "Quero ser exemplo pra minhas filhas.",
  "A explicação sobre gordura corporal foi esclarecedora.",
  "Nunca imaginei que poderia emagrecer comendo pão.",
  "Já fiz de tudo, agora é minha última tentativa.",
  "Tô torcendo pra não perder minha vaga.",
  "Quero ter meu depoimento aqui um dia.",
  "A explicação do tripé foi perfeita!",
  "Nunca vi tanta clareza em uma live só.",
  "Já quero começar o protocolo amanhã mesmo.",
  "Meu sonho é nunca mais sofrer com o peso.",
  "Se eu conseguir, prometo ser a maior defensora desse método.",
  "Já mandei pra minha mãe assistir junto.",
  "Quero perder peso pra voltar a me amar.",
  "Amei saber que não precisa de academia.",
  "Já cansei de sofrer, agora vou até o fim.",
  "Se funcionar, vai ser um novo começo pra mim.",
  "Nunca vi tanta gente animada ao mesmo tempo.",
  "A parte do acompanhamento individual foi o que mais gostei.",
  "Já quero garantir minha vaga agora.",
  "Meu maior sonho é ser feliz com meu corpo.",
  "Se eu conseguir, vai ser o melhor dia da minha vida.",
  "Amei saber que não tem efeito colateral.",
  "Já compartilhei o vídeo com todo mundo!",
  "Quero ser inspiração pra outras mulheres também.",
  "A energia desse grupo é contagiante.",
  "Já mandei mensagem no WhatsApp pra saber mais.",
  "Se eu conseguir emagrecer, vou indicar pra todo mundo!",
  "Já tô pronta pra mudar de vida.",
  "Nunca vi tanta informação útil numa live só.",
  "Quero começar o quanto antes!",
  "Meu sonho é me olhar no espelho e gostar do que vejo.",
  "A explicação sobre efeito sanfona foi tudo pra mim.",
  "Se funcionar, vou ser eternamente grata.",
  "Já quero ser a próxima a dar depoimento.",
  "Nunca vi nutricionista tão próximo dos alunos.",
  "Já tô dentro, agora é esperar minha vez.",
  "Quero mudar minha vida, chega de sofrimento.",
  "Se eu conseguir, vou comemorar muito!",
  "Já indiquei pra todas as minhas amigas.",
  "Amei saber que tem grupo VIP pra tirar dúvidas.",
  "Se eu conseguir emagrecer, vou ajudar outras mulheres também.",
  "Já compartilhei o vídeo no grupo da família.",
  "Quero ser a próxima transformação a aparecer aqui.",
  "Nunca vi tanto apoio numa live só.",
  "Já quero garantir minha vaga antes que acabe.",
  "Se funcionar, nunca mais faço dieta maluca.",
  "Já mandei mensagem pra tirar dúvidas.",
  "Amei saber que o protocolo é aprovado pela ANVISA.",
  "Nunca vi tanta mulher animada ao mesmo tempo.",
  "Quero aprender tudo pra nunca mais engordar.",
  "Se funcionar, vai ser a melhor coisa da minha vida.",
  "Já tô animada pra começar o protocolo.",
  "Quero ser exemplo de superação pra minha família.",
  "Amei saber que não precisa de ingredientes caros.",
  "Já indiquei pra minha nutricionista.",
  "Se eu conseguir, prometo contar minha história aqui.",
  "Nunca vi tanta energia positiva numa live só.",
  "Já tô dentro, agora é esperar o resultado!",
  "Quero aprender a me alimentar sem culpa.",
  "Se eu conseguir emagrecer, vou ser a maior fã desse método.",
  "Já compartilhei com todo mundo!",
  "Amei saber que tem acompanhamento individual.",
  "Se funcionar, vai ser um divisor de águas na minha vida.",
  "Já tô pronta pra mudar de vida, agora vai!",
  "Quero aprender a manter o peso pra sempre.",
  "Se eu conseguir, prometo inspirar outras mulheres também.",
  "Já mandei mensagem no WhatsApp pra saber mais.",
  "Nunca vi tanta verdade numa live só.",
  "Já tô animada pra começar!",
  "Quero ser a próxima história de sucesso.",
  "Se funcionar, vai ser o melhor investimento que já fiz.",
  "Já compartilhei o vídeo com minha família.",
  "Amei a energia desse grupo, obrigada Douglas!",
  "Nunca imaginei que um vídeo mudaria minha vida.",
  "Já quero garantir minha vaga agora!",
  "Se eu conseguir, vou comemorar muito!",
  "Já indiquei pra todas as minhas amigas.",
  "Amei saber que tem grupo VIP pra tirar dúvidas.",
  "Se eu conseguir emagrecer, vou ajudar outras mulheres também.",
  "Já compartilhei o vídeo no grupo da família.",
  "Quero ser a próxima transformação a aparecer aqui.",
  "Nunca vi tanto apoio numa live só.",
  "Já quero garantir minha vaga antes que acabe.",
  "Se funcionar, nunca mais faço dieta maluca.",
  "Já mandei mensagem pra tirar dúvidas.",
  "Amei saber que o protocolo é aprovado pela ANVISA.",
  "Nunca vi tanta mulher animada ao mesmo tempo.",
  "Quero aprender tudo pra nunca mais engordar.",
  "Se funcionar, vai ser a melhor coisa da minha vida.",
  "Já tô animada pra começar o protocolo.",
  "Quero ser exemplo de superação pra minha família."
];

